# Generated by Django 4.2.3 on 2023-11-22 12:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0013_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetranslation",
            name="components",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="templatetranslation",
            name="features",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32), default=list, size=None
            ),
        ),
    ]
