# Generated by Django 4.2.8 on 2023-12-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0018_remove_templatetranslation_country_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="templatetranslation",
            index=models.Index(fields=["channel", "external_id"], name="templates_trans_by_chan_extid"),
        ),
    ]
