# Generated by Django 4.2.8 on 2024-03-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0021_alter_templatetranslation_components"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetranslation",
            name="raw_components",
            field=models.JSONField(default=list),
        ),
    ]
