# Generated by Django 6.0.7 on 2026-07-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0048_alter_templatetranslation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
