# Generated by Django 5.0.4 on 2024-06-11 17:40

from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ("airtime", "0029_populate_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airtimetransfer",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, unique=True),
        ),
    ]
