# Generated by Django 5.2.14 on 2026-05-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airtime", "0039_write_transfer_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airtimetransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("S", "Success"),
                    ("F", "Failed"),
                    ("R", "Reversed"),
                ],
                max_length=1,
            ),
        ),
    ]
