# Generated by Django 5.2.14 on 2026-05-28 16:05

from django.db import migrations, models


def remap_failed_to_rejected(apps, schema_editor):
    AirtimeTransfer = apps.get_model("airtime", "AirtimeTransfer")
    AirtimeTransfer.objects.filter(status="F").update(status="J")


class Migration(migrations.Migration):
    dependencies = [
        ("airtime", "0040_alter_airtimetransfer_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airtimetransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Created"),
                    ("C", "Confirmed"),
                    ("J", "Rejected"),
                    ("A", "Cancelled"),
                    ("B", "Submitted"),
                    ("S", "Completed"),
                    ("R", "Reversed"),
                    ("D", "Declined"),
                ],
                max_length=1,
            ),
        ),
        migrations.RunPython(remap_failed_to_rejected, migrations.RunPython.noop),
    ]
