# Generated by Django 6.0.7 on 2026-07-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airtime", "0041_update_status_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airtimetransfer",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
