# Generated by Django 2.2.4 on 2020-04-28 18:04

from django.db import migrations, models


def update_orgs_to_topup_plan(apps, schema_editor):  # pragma: no cover
    Org = apps.get_model("orgs", "Org")
    Org.objects.all().update(plan="topup")


class Migration(migrations.Migration):

    dependencies = [("orgs", "0060_backuptoken")]

    operations = [
        migrations.RunPython(update_orgs_to_topup_plan),
        migrations.AlterField(
            model_name="org", name="plan", field=models.CharField(max_length=16, null=True, verbose_name="Plan")
        ),
        migrations.RemoveField(model_name="org", name="plan_start"),
    ]
