# Generated by Django 2.2.4 on 2020-06-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0062_orgactivity"),
    ]

    operations = [
        migrations.RemoveField(model_name="org", name="plan",),
        migrations.RemoveField(model_name="org", name="plan_start",),
    ]
