# Generated by Django 2.2.4 on 2020-06-15 21:38

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orgs", "0063_auto_20200615_2054"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("num_contacts", models.IntegerField(verbose_name="Number of contacts allowed")),
                ("num_child_orgs", models.IntegerField(verbose_name="Number of child orgs allowed")),
                ("price", models.IntegerField(default=0)),
                ("uses_topups", models.BooleanField(default=False, help_text="Whether this is a topup-based plan")),
                (
                    "is_custom",
                    models.BooleanField(default=False, help_text="Whether this is a customized plan for a single org"),
                ),
                ("config", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orgs_plan_creations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orgs_plan_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="org",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The current usage plan",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orgs.Plan",
            ),
        ),
    ]
