# Generated by Django 2.2.4 on 2020-09-17 18:40

from django.db import migrations


def populate_org_owner(apps, schema_editor):
    Org = apps.get_model("orgs", "Org")

    # iterate across every org, populate owner with the first administrator or editor on the account
    for org in Org.objects.all():
        owner = None

        # if the user that created the org is still an admin, they are the owner
        if org.created_by.is_active and org.administrators.filter(id=org.created_by_id).exists():
            owner = org.created_by

        # first admin as backdown
        if not owner:
            owner = org.administrators.filter(is_active=True).order_by("id").first()

        # first editor as backdown
        if not owner:
            owner = org.editors.filter(is_active=True).order_by("id").first()

        # first viewer as backdown
        if not owner:
            owner = org.viewers.filter(is_active=True).order_by("id").first()

        # if we have an owner set it, some orgs will have no owner, that's ok
        if owner:
            org.owner = owner
            org.save(update_fields=["owner"])


def reverse(apps, schema_editor):  # pragma: no cover
    pass


def apply_manual():  # pragma: no cover
    from django.apps import apps

    populate_org_owner(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0069_auto_20200917_1839"),
    ]

    operations = [migrations.RunPython(populate_org_owner, reverse)]
