# Generated by Django 2.2.19 on 2021-04-07 14:22

from django.db import migrations

import temba.utils.json
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0080_auto_20210325_1059"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="config",
            field=temba.utils.models.JSONField(default=dict, encoder=temba.utils.json.TembaEncoder),
        ),
    ]
