# Generated by Django 5.1.4 on 2025-01-10 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0033_location_locationalias_location_locations_by_name_and_more"),
        ("orgs", "0164_remove_viewers"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="location",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="locations.location"),
        ),
    ]
