# Generated by Django 5.1.4 on 2025-01-09 17:51

from django.db import migrations


def clear_org_country_field(apps, schema_editor):
    Org = apps.get_model("orgs", "Org")

    orgs = Org.objects.all().exclude(country=None)
    if orgs:
        orgs.update(country=None)


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0165_org_location"),
    ]

    operations = [migrations.RunPython(clear_org_country_field, migrations.RunPython.noop)]
