# Generated by Django 5.1.4 on 2025-01-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0166_clear_org_country_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="org",
            name="country",
        ),
    ]
