# Generated by Django 5.1.4 on 2025-02-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0169_delete_usersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="language",
            field=models.CharField(
                choices=[("en-us", "English")],
                default="en-us",
                help_text="Default website language for new users.",
                max_length=64,
                null=True,
                verbose_name="Default Language",
            ),
        ),
    ]
