# Generated by Django 5.2.10 on 2026-02-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0178_alter_orgimport_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgmembership",
            name="can_assign",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="orgmembership",
            name="can_reply",
            field=models.BooleanField(default=True),
        ),
    ]
