# Generated by Django 5.2.12 on 2026-04-01 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0037_squashed"),
        ("orgs", "0179_orgmembership_can_assign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="root_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="locations.adminboundary",
            ),
        ),
    ]
