# Generated by Django 5.2.12 on 2026-04-01 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0180_org_locations"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE orgs_org SET root_location_id = country_id WHERE country_id IS NOT NULL AND root_location_id IS NULL",
        ),
    ]
