# Generated by Django 5.2.12 on 2026-04-02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0181_backfill_org_locations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="org",
            name="country",
        ),
    ]
