# Generated by Django 5.2.14 on 2026-07-08 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0037_squashed"),
        ("orgs", "0183_backfill_suspended_on"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="org",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_suspended", True), ("suspended_on__isnull", False)),
                    models.Q(("is_suspended", False), ("suspended_on__isnull", True)),
                    _connector="OR",
                ),
                name="orgs_org_suspended_on_consistent",
            ),
        ),
    ]
