# Generated by Django 6.0.7; hand-edited to keep contacts_contact FK columns as int so the
# large contacts_contact table is not rewritten. Postgres allows an int FK column to reference a
# bigint primary key, so contacts_contact's foreign keys are dropped and re-added (via the SQL
# below) without widening the columns. Constraint names are preserved so the operation is
# reversible. Django's model state still treats these columns as bigint (state_operations), so
# makemigrations stays clean.

from django.db import migrations, models

FORWARD_SQL = """
--
-- Alter field id on export
--
SET CONSTRAINTS "notifications_notification_export_id_958a3d15_fk_orgs_export_id" IMMEDIATE; ALTER TABLE "notifications_notification" DROP CONSTRAINT "notifications_notification_export_id_958a3d15_fk_orgs_export_id";
ALTER TABLE "orgs_export" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "orgs_export_id_seq" AS bigint;
ALTER TABLE "notifications_notification" ALTER COLUMN "export_id" TYPE bigint USING "export_id"::bigint;
ALTER TABLE "notifications_notification" ADD CONSTRAINT "notifications_notification_export_id_958a3d15_fk_orgs_export_id" FOREIGN KEY ("export_id") REFERENCES "orgs_export" ("id") DEFERRABLE INITIALLY DEFERRED;
--
-- Alter field id on invitation
--
ALTER TABLE "orgs_invitation" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "orgs_invitation_id_seq" AS bigint;
--
-- Alter field id on org
--
SET CONSTRAINTS "locations_boundaryalias_org_id_930a8491_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "locations_boundaryalias" DROP CONSTRAINT "locations_boundaryalias_org_id_930a8491_fk_orgs_org_id";
SET CONSTRAINTS "ivr_call_org_id_f05ab39d_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "ivr_call" DROP CONSTRAINT "ivr_call_org_id_f05ab39d_fk_orgs_org_id";
SET CONSTRAINTS "channels_channelevent_org_id_4d7fff63_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "channels_channelevent" DROP CONSTRAINT "channels_channelevent_org_id_4d7fff63_fk_orgs_org_id";
SET CONSTRAINTS "channels_channel_org_id_fd34a95a_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "channels_channel" DROP CONSTRAINT "channels_channel_org_id_fd34a95a_fk_orgs_org_id";
SET CONSTRAINTS "orgs_org_parent_id_79ba1bbf_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "orgs_org" DROP CONSTRAINT "orgs_org_parent_id_79ba1bbf_fk_orgs_org_id";
SET CONSTRAINTS "contacts_contactimport_org_id_b7820a48_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "contacts_contactimport" DROP CONSTRAINT "contacts_contactimport_org_id_b7820a48_fk_orgs_org_id";
SET CONSTRAINTS "contacts_contactfire_org_id_9dc80e0c_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "contacts_contactfire" DROP CONSTRAINT "contacts_contactfire_org_id_9dc80e0c_fk_orgs_org_id";
SET CONSTRAINTS "contacts_contact_org_id_01d86aa4_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "contacts_contact" DROP CONSTRAINT "contacts_contact_org_id_01d86aa4_fk_orgs_org_id";
SET CONSTRAINTS "orgs_itemcount_org_id_604bb8db_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "orgs_itemcount" DROP CONSTRAINT "orgs_itemcount_org_id_604bb8db_fk_orgs_org_id";
SET CONSTRAINTS "orgs_dailycount_org_id_e73b93d3_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "orgs_dailycount" DROP CONSTRAINT "orgs_dailycount_org_id_e73b93d3_fk_orgs_org_id";
SET CONSTRAINTS "orgs_export_org_id_3d9eebc7_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "orgs_export" DROP CONSTRAINT "orgs_export_org_id_3d9eebc7_fk_orgs_org_id";
SET CONSTRAINTS "contacts_contactfield_org_id_d83cc86a_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "contacts_contactfield" DROP CONSTRAINT "contacts_contactfield_org_id_d83cc86a_fk_orgs_org_id";
SET CONSTRAINTS "flows_flowlabel_org_id_4ed2f553_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "flows_flowlabel" DROP CONSTRAINT "flows_flowlabel_org_id_4ed2f553_fk_orgs_org_id";
SET CONSTRAINTS "flows_flowstart_org_id_d5383c58_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "flows_flowstart" DROP CONSTRAINT "flows_flowstart_org_id_d5383c58_fk_orgs_org_id";
SET CONSTRAINTS "flows_flow_org_id_51b9c589_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "flows_flow" DROP CONSTRAINT "flows_flow_org_id_51b9c589_fk_orgs_org_id";
SET CONSTRAINTS "contacts_contactgroup_org_id_be850815_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "contacts_contactgroup" DROP CONSTRAINT "contacts_contactgroup_org_id_be850815_fk_orgs_org_id";
SET CONSTRAINTS "orgs_orgimport_org_id_d9346c57_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "orgs_orgimport" DROP CONSTRAINT "orgs_orgimport_org_id_d9346c57_fk_orgs_org_id";
SET CONSTRAINTS "notifications_incident_org_id_b5cb2702_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "notifications_incident" DROP CONSTRAINT "notifications_incident_org_id_b5cb2702_fk_orgs_org_id";
SET CONSTRAINTS "orgs_invitation_org_id_d9d2be95_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "orgs_invitation" DROP CONSTRAINT "orgs_invitation_org_id_d9d2be95_fk_orgs_org_id";
SET CONSTRAINTS "ai_llm_org_id_21c1fd13_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "ai_llm" DROP CONSTRAINT "ai_llm_org_id_21c1fd13_fk_orgs_org_id";
SET CONSTRAINTS "notifications_notification_org_id_b4c202e9_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "notifications_notification" DROP CONSTRAINT "notifications_notification_org_id_b4c202e9_fk_orgs_org_id";
SET CONSTRAINTS "orgs_orgmembership_org_id_35cc8172_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "orgs_orgmembership" DROP CONSTRAINT "orgs_orgmembership_org_id_35cc8172_fk_orgs_org_id";
SET CONSTRAINTS "flows_flowrun_org_id_07d5f694_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "flows_flowrun" DROP CONSTRAINT "flows_flowrun_org_id_07d5f694_fk_orgs_org_id";
SET CONSTRAINTS "tickets_shortcut_org_id_5fbbda6f_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "tickets_shortcut" DROP CONSTRAINT "tickets_shortcut_org_id_5fbbda6f_fk_orgs_org_id";
SET CONSTRAINTS "tickets_team_org_id_2a011111_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "tickets_team" DROP CONSTRAINT "tickets_team_org_id_2a011111_fk_orgs_org_id";
SET CONSTRAINTS "tickets_ticket_org_id_56b25ecf_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "tickets_ticket" DROP CONSTRAINT "tickets_ticket_org_id_56b25ecf_fk_orgs_org_id";
SET CONSTRAINTS "tickets_topic_org_id_0b22bd8a_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "tickets_topic" DROP CONSTRAINT "tickets_topic_org_id_0b22bd8a_fk_orgs_org_id";
SET CONSTRAINTS "contacts_contacturn_org_id_3cc60a3a_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "contacts_contacturn" DROP CONSTRAINT "contacts_contacturn_org_id_3cc60a3a_fk_orgs_org_id";
ALTER TABLE "orgs_org" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "orgs_org_id_seq" AS bigint;
ALTER TABLE "locations_boundaryalias" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "ivr_call" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "channels_channelevent" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "channels_channel" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "orgs_org" ALTER COLUMN "parent_id" TYPE bigint USING "parent_id"::bigint;
ALTER TABLE "contacts_contactimport" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "contacts_contactfire" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "orgs_itemcount" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "orgs_dailycount" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "orgs_export" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "contacts_contactfield" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "flows_flowlabel" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "flows_flowstart" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "flows_flow" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "contacts_contactgroup" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "orgs_orgimport" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "notifications_incident" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "orgs_invitation" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "ai_llm" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "notifications_notification" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "orgs_orgmembership" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "flows_flowrun" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "tickets_shortcut" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "tickets_team" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "tickets_ticket" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "tickets_topic" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "contacts_contacturn" ALTER COLUMN "org_id" TYPE bigint USING "org_id"::bigint;
ALTER TABLE "locations_boundaryalias" ADD CONSTRAINT "locations_boundaryalias_org_id_930a8491_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ivr_call" ADD CONSTRAINT "ivr_call_org_id_f05ab39d_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "channels_channelevent" ADD CONSTRAINT "channels_channelevent_org_id_4d7fff63_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "channels_channel" ADD CONSTRAINT "channels_channel_org_id_fd34a95a_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_org" ADD CONSTRAINT "orgs_org_parent_id_79ba1bbf_fk_orgs_org_id" FOREIGN KEY ("parent_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactimport" ADD CONSTRAINT "contacts_contactimport_org_id_b7820a48_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactfire" ADD CONSTRAINT "contacts_contactfire_org_id_9dc80e0c_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contact" ADD CONSTRAINT "contacts_contact_org_id_01d86aa4_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_itemcount" ADD CONSTRAINT "orgs_itemcount_org_id_604bb8db_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_dailycount" ADD CONSTRAINT "orgs_dailycount_org_id_e73b93d3_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_export" ADD CONSTRAINT "orgs_export_org_id_3d9eebc7_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactfield" ADD CONSTRAINT "contacts_contactfield_org_id_d83cc86a_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowlabel" ADD CONSTRAINT "flows_flowlabel_org_id_4ed2f553_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowstart" ADD CONSTRAINT "flows_flowstart_org_id_d5383c58_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow" ADD CONSTRAINT "flows_flow_org_id_51b9c589_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactgroup" ADD CONSTRAINT "contacts_contactgroup_org_id_be850815_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_orgimport" ADD CONSTRAINT "orgs_orgimport_org_id_d9346c57_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "notifications_incident" ADD CONSTRAINT "notifications_incident_org_id_b5cb2702_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_invitation" ADD CONSTRAINT "orgs_invitation_org_id_d9d2be95_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ai_llm" ADD CONSTRAINT "ai_llm_org_id_21c1fd13_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "notifications_notification" ADD CONSTRAINT "notifications_notification_org_id_b4c202e9_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_orgmembership" ADD CONSTRAINT "orgs_orgmembership_org_id_35cc8172_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowrun" ADD CONSTRAINT "flows_flowrun_org_id_07d5f694_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_shortcut" ADD CONSTRAINT "tickets_shortcut_org_id_5fbbda6f_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_team" ADD CONSTRAINT "tickets_team_org_id_2a011111_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_ticket" ADD CONSTRAINT "tickets_ticket_org_id_56b25ecf_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_topic" ADD CONSTRAINT "tickets_topic_org_id_0b22bd8a_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contacturn" ADD CONSTRAINT "contacts_contacturn_org_id_3cc60a3a_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
--
-- Alter field id on orgimport
--
ALTER TABLE "orgs_orgimport" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "orgs_orgimport_id_seq" AS bigint;
--
-- Alter field id on orgmembership
--
ALTER TABLE "orgs_orgmembership" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "orgs_orgmembership_id_seq" AS bigint;
"""

REVERSE_SQL = """
--
-- Alter field id on orgmembership
--
ALTER TABLE "orgs_orgmembership" ALTER COLUMN "id" TYPE integer USING "id"::integer;
ALTER SEQUENCE IF EXISTS "orgs_orgmembership_id_seq" AS integer;
--
-- Alter field id on orgimport
--
ALTER TABLE "orgs_orgimport" ALTER COLUMN "id" TYPE integer USING "id"::integer;
ALTER SEQUENCE IF EXISTS "orgs_orgimport_id_seq" AS integer;
--
-- Alter field id on org
--
SET CONSTRAINTS "locations_boundaryalias_org_id_930a8491_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "locations_boundaryalias" DROP CONSTRAINT "locations_boundaryalias_org_id_930a8491_fk_orgs_org_id";
SET CONSTRAINTS "msgs_broadcast_org_id_78c94f15_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "msgs_broadcast" DROP CONSTRAINT "msgs_broadcast_org_id_78c94f15_fk_orgs_org_id";
SET CONSTRAINTS "ivr_call_org_id_f05ab39d_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "ivr_call" DROP CONSTRAINT "ivr_call_org_id_f05ab39d_fk_orgs_org_id";
SET CONSTRAINTS "channels_channelevent_org_id_4d7fff63_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "channels_channelevent" DROP CONSTRAINT "channels_channelevent_org_id_4d7fff63_fk_orgs_org_id";
SET CONSTRAINTS "channels_channel_org_id_fd34a95a_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "channels_channel" DROP CONSTRAINT "channels_channel_org_id_fd34a95a_fk_orgs_org_id";
SET CONSTRAINTS "orgs_org_parent_id_79ba1bbf_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "orgs_org" DROP CONSTRAINT "orgs_org_parent_id_79ba1bbf_fk_orgs_org_id";
SET CONSTRAINTS "contacts_contactimport_org_id_b7820a48_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "contacts_contactimport" DROP CONSTRAINT "contacts_contactimport_org_id_b7820a48_fk_orgs_org_id";
SET CONSTRAINTS "contacts_contactfire_org_id_9dc80e0c_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "contacts_contactfire" DROP CONSTRAINT "contacts_contactfire_org_id_9dc80e0c_fk_orgs_org_id";
SET CONSTRAINTS "contacts_contact_org_id_01d86aa4_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "contacts_contact" DROP CONSTRAINT "contacts_contact_org_id_01d86aa4_fk_orgs_org_id";
SET CONSTRAINTS "orgs_itemcount_org_id_604bb8db_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "orgs_itemcount" DROP CONSTRAINT "orgs_itemcount_org_id_604bb8db_fk_orgs_org_id";
SET CONSTRAINTS "orgs_dailycount_org_id_e73b93d3_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "orgs_dailycount" DROP CONSTRAINT "orgs_dailycount_org_id_e73b93d3_fk_orgs_org_id";
SET CONSTRAINTS "orgs_export_org_id_3d9eebc7_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "orgs_export" DROP CONSTRAINT "orgs_export_org_id_3d9eebc7_fk_orgs_org_id";
SET CONSTRAINTS "contacts_contactfield_org_id_d83cc86a_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "contacts_contactfield" DROP CONSTRAINT "contacts_contactfield_org_id_d83cc86a_fk_orgs_org_id";
SET CONSTRAINTS "flows_flowlabel_org_id_4ed2f553_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "flows_flowlabel" DROP CONSTRAINT "flows_flowlabel_org_id_4ed2f553_fk_orgs_org_id";
SET CONSTRAINTS "flows_flowstart_org_id_d5383c58_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "flows_flowstart" DROP CONSTRAINT "flows_flowstart_org_id_d5383c58_fk_orgs_org_id";
SET CONSTRAINTS "flows_flow_org_id_51b9c589_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "flows_flow" DROP CONSTRAINT "flows_flow_org_id_51b9c589_fk_orgs_org_id";
SET CONSTRAINTS "contacts_contactgroup_org_id_be850815_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "contacts_contactgroup" DROP CONSTRAINT "contacts_contactgroup_org_id_be850815_fk_orgs_org_id";
SET CONSTRAINTS "orgs_orgimport_org_id_d9346c57_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "orgs_orgimport" DROP CONSTRAINT "orgs_orgimport_org_id_d9346c57_fk_orgs_org_id";
SET CONSTRAINTS "notifications_incident_org_id_b5cb2702_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "notifications_incident" DROP CONSTRAINT "notifications_incident_org_id_b5cb2702_fk_orgs_org_id";
SET CONSTRAINTS "orgs_invitation_org_id_d9d2be95_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "orgs_invitation" DROP CONSTRAINT "orgs_invitation_org_id_d9d2be95_fk_orgs_org_id";
SET CONSTRAINTS "ai_llm_org_id_21c1fd13_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "ai_llm" DROP CONSTRAINT "ai_llm_org_id_21c1fd13_fk_orgs_org_id";
SET CONSTRAINTS "msgs_media_org_id_5e6f5372_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "msgs_media" DROP CONSTRAINT "msgs_media_org_id_5e6f5372_fk_orgs_org_id";
SET CONSTRAINTS "msgs_msg_org_id_d3488a20_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "msgs_msg" DROP CONSTRAINT "msgs_msg_org_id_d3488a20_fk_orgs_org_id";
SET CONSTRAINTS "msgs_label_org_id_a63db233_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "msgs_label" DROP CONSTRAINT "msgs_label_org_id_a63db233_fk_orgs_org_id";
SET CONSTRAINTS "notifications_notification_org_id_b4c202e9_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "notifications_notification" DROP CONSTRAINT "notifications_notification_org_id_b4c202e9_fk_orgs_org_id";
SET CONSTRAINTS "msgs_optin_org_id_554c3552_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "msgs_optin" DROP CONSTRAINT "msgs_optin_org_id_554c3552_fk_orgs_org_id";
SET CONSTRAINTS "orgs_orgmembership_org_id_35cc8172_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "orgs_orgmembership" DROP CONSTRAINT "orgs_orgmembership_org_id_35cc8172_fk_orgs_org_id";
SET CONSTRAINTS "flows_flowrun_org_id_07d5f694_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "flows_flowrun" DROP CONSTRAINT "flows_flowrun_org_id_07d5f694_fk_orgs_org_id";
SET CONSTRAINTS "schedules_schedule_org_id_bb6269db_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "schedules_schedule" DROP CONSTRAINT "schedules_schedule_org_id_bb6269db_fk_orgs_org_id";
SET CONSTRAINTS "tickets_shortcut_org_id_5fbbda6f_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "tickets_shortcut" DROP CONSTRAINT "tickets_shortcut_org_id_5fbbda6f_fk_orgs_org_id";
SET CONSTRAINTS "tickets_team_org_id_2a011111_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "tickets_team" DROP CONSTRAINT "tickets_team_org_id_2a011111_fk_orgs_org_id";
SET CONSTRAINTS "tickets_ticket_org_id_56b25ecf_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "tickets_ticket" DROP CONSTRAINT "tickets_ticket_org_id_56b25ecf_fk_orgs_org_id";
SET CONSTRAINTS "tickets_topic_org_id_0b22bd8a_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "tickets_topic" DROP CONSTRAINT "tickets_topic_org_id_0b22bd8a_fk_orgs_org_id";
SET CONSTRAINTS "contacts_contacturn_org_id_3cc60a3a_fk_orgs_org_id" IMMEDIATE; ALTER TABLE "contacts_contacturn" DROP CONSTRAINT "contacts_contacturn_org_id_3cc60a3a_fk_orgs_org_id";
ALTER TABLE "orgs_org" ALTER COLUMN "id" TYPE integer USING "id"::integer;
ALTER SEQUENCE IF EXISTS "orgs_org_id_seq" AS integer;
ALTER TABLE "locations_boundaryalias" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "msgs_broadcast" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "ivr_call" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "channels_channelevent" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "channels_channel" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "orgs_org" ALTER COLUMN "parent_id" TYPE integer USING "parent_id"::integer;
ALTER TABLE "contacts_contactimport" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "contacts_contactfire" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "orgs_itemcount" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "orgs_dailycount" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "orgs_export" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "contacts_contactfield" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "flows_flowlabel" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "flows_flowstart" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "flows_flow" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "contacts_contactgroup" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "orgs_orgimport" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "notifications_incident" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "orgs_invitation" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "ai_llm" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "msgs_media" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "msgs_msg" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "msgs_label" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "notifications_notification" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "msgs_optin" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "orgs_orgmembership" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "flows_flowrun" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "schedules_schedule" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "tickets_shortcut" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "tickets_team" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "tickets_ticket" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "tickets_topic" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "contacts_contacturn" ALTER COLUMN "org_id" TYPE integer USING "org_id"::integer;
ALTER TABLE "locations_boundaryalias" ADD CONSTRAINT "locations_boundaryalias_org_id_930a8491_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "msgs_broadcast" ADD CONSTRAINT "msgs_broadcast_org_id_78c94f15_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ivr_call" ADD CONSTRAINT "ivr_call_org_id_f05ab39d_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "channels_channelevent" ADD CONSTRAINT "channels_channelevent_org_id_4d7fff63_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "channels_channel" ADD CONSTRAINT "channels_channel_org_id_fd34a95a_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_org" ADD CONSTRAINT "orgs_org_parent_id_79ba1bbf_fk_orgs_org_id" FOREIGN KEY ("parent_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactimport" ADD CONSTRAINT "contacts_contactimport_org_id_b7820a48_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactfire" ADD CONSTRAINT "contacts_contactfire_org_id_9dc80e0c_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contact" ADD CONSTRAINT "contacts_contact_org_id_01d86aa4_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_itemcount" ADD CONSTRAINT "orgs_itemcount_org_id_604bb8db_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_dailycount" ADD CONSTRAINT "orgs_dailycount_org_id_e73b93d3_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_export" ADD CONSTRAINT "orgs_export_org_id_3d9eebc7_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactfield" ADD CONSTRAINT "contacts_contactfield_org_id_d83cc86a_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowlabel" ADD CONSTRAINT "flows_flowlabel_org_id_4ed2f553_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowstart" ADD CONSTRAINT "flows_flowstart_org_id_d5383c58_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow" ADD CONSTRAINT "flows_flow_org_id_51b9c589_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactgroup" ADD CONSTRAINT "contacts_contactgroup_org_id_be850815_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_orgimport" ADD CONSTRAINT "orgs_orgimport_org_id_d9346c57_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "notifications_incident" ADD CONSTRAINT "notifications_incident_org_id_b5cb2702_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_invitation" ADD CONSTRAINT "orgs_invitation_org_id_d9d2be95_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ai_llm" ADD CONSTRAINT "ai_llm_org_id_21c1fd13_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "msgs_media" ADD CONSTRAINT "msgs_media_org_id_5e6f5372_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "msgs_msg" ADD CONSTRAINT "msgs_msg_org_id_d3488a20_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "msgs_label" ADD CONSTRAINT "msgs_label_org_id_a63db233_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "notifications_notification" ADD CONSTRAINT "notifications_notification_org_id_b4c202e9_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "msgs_optin" ADD CONSTRAINT "msgs_optin_org_id_554c3552_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_orgmembership" ADD CONSTRAINT "orgs_orgmembership_org_id_35cc8172_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowrun" ADD CONSTRAINT "flows_flowrun_org_id_07d5f694_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "schedules_schedule" ADD CONSTRAINT "schedules_schedule_org_id_bb6269db_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_shortcut" ADD CONSTRAINT "tickets_shortcut_org_id_5fbbda6f_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_team" ADD CONSTRAINT "tickets_team_org_id_2a011111_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_ticket" ADD CONSTRAINT "tickets_ticket_org_id_56b25ecf_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_topic" ADD CONSTRAINT "tickets_topic_org_id_0b22bd8a_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contacturn" ADD CONSTRAINT "contacts_contacturn_org_id_3cc60a3a_fk_orgs_org_id" FOREIGN KEY ("org_id") REFERENCES "orgs_org" ("id") DEFERRABLE INITIALLY DEFERRED;
--
-- Alter field id on invitation
--
ALTER TABLE "orgs_invitation" ALTER COLUMN "id" TYPE integer USING "id"::integer;
ALTER SEQUENCE IF EXISTS "orgs_invitation_id_seq" AS integer;
--
-- Alter field id on export
--
SET CONSTRAINTS "notifications_notification_export_id_958a3d15_fk_orgs_export_id" IMMEDIATE; ALTER TABLE "notifications_notification" DROP CONSTRAINT "notifications_notification_export_id_958a3d15_fk_orgs_export_id";
ALTER TABLE "orgs_export" ALTER COLUMN "id" TYPE integer USING "id"::integer;
ALTER SEQUENCE IF EXISTS "orgs_export_id_seq" AS integer;
ALTER TABLE "notifications_notification" ALTER COLUMN "export_id" TYPE integer USING "export_id"::integer;
ALTER TABLE "notifications_notification" ADD CONSTRAINT "notifications_notification_export_id_958a3d15_fk_orgs_export_id" FOREIGN KEY ("export_id") REFERENCES "orgs_export" ("id") DEFERRABLE INITIALLY DEFERRED;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0185_normalize_timezones"),
        # so unapplying doesn't try to alter FKs on the dropped tables
        ("classifiers", "0018_delete_classifier_intent"),
        ("tickets", "0087_delete_ticketevent"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="export",
                    name="id",
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                migrations.AlterField(
                    model_name="invitation",
                    name="id",
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                migrations.AlterField(
                    model_name="org",
                    name="id",
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                migrations.AlterField(
                    model_name="orgimport",
                    name="id",
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                migrations.AlterField(
                    model_name="orgmembership",
                    name="id",
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
            ],
            database_operations=[migrations.RunSQL(FORWARD_SQL, reverse_sql=REVERSE_SQL)],
        ),
    ]
