# Generated by Django 5.2.14 on 2026-07-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0185_normalize_timezones"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgmembership",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
