# Generated by Django 6.0.7 on 2026-07-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0185_normalize_timezones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="export",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="orgimport",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="orgmembership",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
