# Generated by Django 6.0.7 on 2026-07-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0186_alter_export_id_alter_invitation_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="language",
            field=models.CharField(
                choices=[
                    ("en-us", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("pt-br", "Portuguese"),
                ],
                default="en-us",
                help_text="Default website language for new users.",
                max_length=64,
                null=True,
                verbose_name="Default Language",
            ),
        ),
    ]
