# Generated by Django 6.1 on 2026-09-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("orgs", "0188_reset_dropped_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="admin_groups",
            field=models.ManyToManyField(related_name="admin_orgs", to="auth.group"),
        ),
    ]
