# Generated by Django 2.1.5 on 2019-01-29 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0021_indexes")]

    operations = [
        migrations.AlterField(
            model_name="webhookevent",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which created this item",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="api_webhookevent_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="api_webhookevent_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
