# Generated by Django 6.0.7 on 2026-07-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0052_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resthook",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="resthooksubscriber",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
