# Generated by Django 5.2.1 on 2025-05-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0022_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="imported",
            field=models.BooleanField(default=False),
        ),
    ]
