# Generated by Django 5.2.9 on 2025-12-19 15:14

import itertools
from collections import defaultdict

from django.core.files.storage import storages
from django.db import migrations


def clear_empty_archive_uploads(apps, schema_editor):
    Archive = apps.get_model("archives", "Archive")
    s3_client = storages["archives"].connection.meta.client
    num_updated = 0

    for batch in itertools.batched(Archive.objects.filter(record_count=0, location__isnull=False).order_by("id"), 100):
        s3_files = defaultdict(list)
        for archive in batch:
            bucket, key = archive.location.split(":", 1)
            s3_files[bucket].append(key)

        for bucket, keys in s3_files.items():
            s3_client.delete_objects(Bucket=bucket, Delete={"Objects": [{"Key": key} for key in keys]})

        Archive.objects.filter(id__in=[a.id for a in batch]).update(location=None, hash=None)

        num_updated += len(batch)
        print(f"Cleared uploads for {num_updated} empty archives")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    clear_empty_archive_uploads(apps, None)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("archives", "0033_alter_archive_uuid"),
    ]

    operations = [
        migrations.RunPython(clear_empty_archive_uploads, reverse_code=migrations.RunPython.noop),
    ]
