# Generated by Django 6.0.7 on 2026-07-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0034_remove_empty_uploads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
