[project]
name = "temba"
version = "10.3.8"
description = "Hosted service for visually building interactive messaging applications"
authors = [
    {"name" = "Nyaruka", "email" = "code@nyaruka.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "psycopg[pool] ~= 3.2.9",
    "django ~= 5.2.1",
    "django-allauth[mfa] (>=65.8.1,<66.0.0)",
    "django-compressor ~= 4.5.1",
    "django-countries ~= 7.6.1",
    "django-formtools ~= 2.5.1",
    "django-imagekit ~= 5.0.0",
    "django-mptt ~= 0.16.0",
    "django-storages ~= 1.14.6",
    "django-timezone-field ~= 6.1.0",
    "django-valkey (>=0.2.1,<0.3.0)",
    "djangorestframework ~= 3.16.0",
    "dj-database-url ~= 0.5.0",
    "smartmin ~= 5.2.2",
    "celery[redis] ~= 5.5.3",
    "boto3 ~= 1.38.36",
    "cryptography ~= 45.0.4",
    "pyotp ~= 2.4.1",
    "geojson ~= 2.5.0",
    "markdown ~= 3.8.0",
    "polib ~= 1.2.0",
    "python-magic ~= 0.4.27",
    "xlsxlite ~= 1.0.0",
    "colorama ~= 0.4.6",
    "gunicorn (>=23.0.0,<24.0.0)",
    "iptools ~= 0.7.0",
    "iso8601 ~= 2.1.0",
    "iso639-lang ~= 2.6.0",
    "phonenumbers ~= 9.0.7",
    "pycountry ~= 24.6.1",
    "python-dateutil ~= 2.9.0",
    "packaging ~= 25.0",
    "requests-toolbelt ~= 1.0.0",
    "chardet ~= 5.2.0",
    "openpyxl ~= 3.1.5",
    "ffmpeg-python ~= 0.2.0",
    "pillow ~= 10.4.0",
    "google-auth ~= 2.32.0",
    "google-genai (>=1.10.0,<2.0.0)",
    "twilio ~= 9.3.7",
    "vonage ~= 3.17.4",
    "slack-sdk ~= 3.17.0",
    "openai (>=1.66.3,<2.0.0)",
    "anthropic (>=0.54.0,<1.0.0)",
    "fido2 (>=2.0.0,<3.0.0)"
]

[project.urls]
repository = "http://github.com/rapidpro/rapidpro"


[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
coverage = { extras = ["toml"], version = "^7.5.4" }
isort = "^5.13.2"
responses = "^0.25.3"
ruff = "^0.5.0"
djlint = "^1.34.1"

[tool.poetry.requires-plugins]
poetry-bumpversion = ">=0.3.3"

[tool.poetry_bumpversion.file."temba/__init__.py"]

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
fix = true

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["E741", "E501", "F405"]

[tool.isort]
multi_line_output = 3
force_grid_wrap = 0
line_length = 120
include_trailing_comma = true
combine_as_imports = true
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "DJANGO",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
known_django = ["django"]

[tool.djlint]
blank_line_after_tag = "load"
custom_blocks = "render,element,slot"
custom_html = "temba-[a-z-]+"
format_css = true
format_js = true
ignore = "H021,H023"
indent = 2
max_attribute_length = 100
max_line_length = 200

[tool.djlint.css]
indent_size = 2

[tool.djlint.js]
indent_size = 2
templating = "django"

[tool.coverage.run]
source = ["./temba"]

[tool.coverage.report]
ignore_errors = true
precision = 0
show_missing = true
skip_covered = true
exclude_lines = [
    "pragma: no cover",
    "pragma: needs cover",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
]
omit = ["**/tests*", "**/tests/*", "*settings*", "**/management/commands/*"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"