# Generated by Django 5.1.4 on 2025-02-28 15:24

from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0066_alter_campaignevent_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignevent",
            name="fire_uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="campaignevent",
            name="fire_uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="status",
            field=models.CharField(choices=[("S", "Scheduling"), ("R", "Ready")], default="R", max_length=1),
        ),
    ]
