# Generated by Django 5.1.4 on 2025-02-28 15:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0066_alter_campaignevent_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignevent",
            name="fire_uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="status",
            field=models.CharField(choices=[("P", "Scheduling"), ("S", "Ready")], default="S", max_length=1),
        ),
    ]
