# Generated by Django 5.1.4 on 2025-02-28 20:53

from django.db import migrations

from temba.utils.uuid import uuid4


def backfill_event_fire_uuid(apps, schema_editor):  # pragma: no cover
    CampaignEvent = apps.get_model("campaigns", "CampaignEvent")

    for event in CampaignEvent.objects.filter(fire_uuid=None).only("id"):
        event.fire_uuid = uuid4()
        event.save(update_fields=("fire_uuid",))


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0067_campaignevent_fire_uuid_campaignevent_status"),
    ]

    operations = [
        migrations.RunPython(backfill_event_fire_uuid, migrations.RunPython.noop),
    ]
