# Generated by Django 5.1.4 on 2025-03-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0068_add_version_to_event_fires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="status",
            field=models.CharField(choices=[("S", "Scheduling"), ("R", "Ready")], default="S", max_length=1),
        ),
    ]
