# Generated by Django 5.1.4 on 2025-02-28 20:55

from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0068_backfill_event_fire_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="fire_uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4),
        ),
    ]
