# Generated by Django 5.1.4 on 2025-03-12 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0074_backfill_campaignevent_translations"),
        ("flows", "0381_remove_flowstart_campaign_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="flow",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="campaign_events", to="flows.flow"
            ),
        ),
    ]
