# Generated by Django 6.0.7 on 2026-07-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0081_campaignevent_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="campaignevent",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
