# Generated by Django 6.0.7 on 2026-08-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0002_backfill_system_knowledge"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="language",
            field=models.CharField(default="eng", max_length=3),
        ),
    ]
