# Generated by Django 6.1.1 on 2026-09-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0003_article_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
