# Generated by Django 5.1.4 on 2025-02-12 21:11

from django.db import migrations


def backfill_name(apps, schema_editor):
    User = apps.get_model("users", "User")

    for user in User.objects.all():
        user.name = f"{user.first_name} {user.last_name}".strip()[:150]
        user.save(update_fields=("name",))


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_name_alter_user_date_joined_and_more"),
    ]

    operations = [migrations.RunPython(backfill_name, migrations.RunPython.noop)]
