# Generated by Django 5.1.9 on 2025-05-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_remove_backuptoken_user_delete_failedlogin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
    ]
