# Generated by Django 5.1.9 on 2025-05-13 14:53

import temba.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_remove_user_email_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, null=True),
        ),
    ]
