# Generated by Django 6.0.7; hand-edited to keep contacts_contact FK columns as int so the
# large contacts_contact table is not rewritten. Postgres allows an int FK column to reference a
# bigint primary key, so contacts_contact's foreign keys are dropped and re-added (via the SQL
# below) without widening the columns. Constraint names are preserved so the operation is
# reversible. Django's model state still treats these columns as bigint (state_operations), so
# makemigrations stays clean.

from django.db import migrations, models

FORWARD_SQL = """
--
-- Alter field id on user
--
SET CONSTRAINTS "contacts_contact_created_by_id_57537352_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contact" DROP CONSTRAINT "contacts_contact_created_by_id_57537352_fk_users_user_id";
SET CONSTRAINTS "contacts_contact_modified_by_id_db5cbe12_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contact" DROP CONSTRAINT "contacts_contact_modified_by_id_db5cbe12_fk_users_user_id";
SET CONSTRAINTS "flows_flowstart_created_by_id_4eb88868_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flowstart" DROP CONSTRAINT "flows_flowstart_created_by_id_4eb88868_fk_users_user_id";
SET CONSTRAINTS "flows_flowstart_modified_by_id_c9a338d3_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flowstart" DROP CONSTRAINT "flows_flowstart_modified_by_id_c9a338d3_fk_users_user_id";
SET CONSTRAINTS "flows_flow_user_dependencies_user_id_9201056c_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flow_user_dependencies" DROP CONSTRAINT "flows_flow_user_dependencies_user_id_9201056c_fk_users_user_id";
SET CONSTRAINTS "users_user_groups_user_id_5f6f5a90_fk_users_user_id" IMMEDIATE; ALTER TABLE "users_user_groups" DROP CONSTRAINT "users_user_groups_user_id_5f6f5a90_fk_users_user_id";
SET CONSTRAINTS "users_user_user_permissions_user_id_20aca447_fk_users_user_id" IMMEDIATE; ALTER TABLE "users_user_user_permissions" DROP CONSTRAINT "users_user_user_permissions_user_id_20aca447_fk_users_user_id";
SET CONSTRAINTS "ai_llm_created_by_id_b141546f_fk_users_user_id" IMMEDIATE; ALTER TABLE "ai_llm" DROP CONSTRAINT "ai_llm_created_by_id_b141546f_fk_users_user_id";
SET CONSTRAINTS "ai_llm_modified_by_id_138573f7_fk_users_user_id" IMMEDIATE; ALTER TABLE "ai_llm" DROP CONSTRAINT "ai_llm_modified_by_id_138573f7_fk_users_user_id";
SET CONSTRAINTS "tickets_ticket_assignee_id_3a5aa407_fk_users_user_id" IMMEDIATE; ALTER TABLE "tickets_ticket" DROP CONSTRAINT "tickets_ticket_assignee_id_3a5aa407_fk_users_user_id";
SET CONSTRAINTS "channels_channel_created_by_id_8141adf4_fk_users_user_id" IMMEDIATE; ALTER TABLE "channels_channel" DROP CONSTRAINT "channels_channel_created_by_id_8141adf4_fk_users_user_id";
SET CONSTRAINTS "channels_channel_modified_by_id_af6bcc5e_fk_users_user_id" IMMEDIATE; ALTER TABLE "channels_channel" DROP CONSTRAINT "channels_channel_modified_by_id_af6bcc5e_fk_users_user_id";
SET CONSTRAINTS "contacts_contactnote_created_by_id_1d4def0c_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contactnote" DROP CONSTRAINT "contacts_contactnote_created_by_id_1d4def0c_fk_users_user_id";
SET CONSTRAINTS "contacts_contactfield_created_by_id_7bce7fd0_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contactfield" DROP CONSTRAINT "contacts_contactfield_created_by_id_7bce7fd0_fk_users_user_id";
SET CONSTRAINTS "contacts_contactfield_modified_by_id_99cfac9b_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contactfield" DROP CONSTRAINT "contacts_contactfield_modified_by_id_99cfac9b_fk_users_user_id";
SET CONSTRAINTS "contacts_contactgroup_created_by_id_6bbeef89_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contactgroup" DROP CONSTRAINT "contacts_contactgroup_created_by_id_6bbeef89_fk_users_user_id";
SET CONSTRAINTS "contacts_contactgroup_modified_by_id_a765a76e_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contactgroup" DROP CONSTRAINT "contacts_contactgroup_modified_by_id_a765a76e_fk_users_user_id";
SET CONSTRAINTS "contacts_contactimport_created_by_id_a34024c3_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contactimport" DROP CONSTRAINT "contacts_contactimport_created_by_id_a34024c3_fk_users_user_id";
SET CONSTRAINTS "contacts_contactimport_modified_by_id_6cf6a8d5_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contactimport" DROP CONSTRAINT "contacts_contactimport_modified_by_id_6cf6a8d5_fk_users_user_id";
SET CONSTRAINTS "orgs_export_created_by_id_c83cb736_fk_users_user_id" IMMEDIATE; ALTER TABLE "orgs_export" DROP CONSTRAINT "orgs_export_created_by_id_c83cb736_fk_users_user_id";
SET CONSTRAINTS "flows_flow_saved_by_id_edb563b6_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flow" DROP CONSTRAINT "flows_flow_saved_by_id_edb563b6_fk_users_user_id";
SET CONSTRAINTS "flows_flow_created_by_id_2e1adcb6_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flow" DROP CONSTRAINT "flows_flow_created_by_id_2e1adcb6_fk_users_user_id";
SET CONSTRAINTS "flows_flow_modified_by_id_493fb4b1_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flow" DROP CONSTRAINT "flows_flow_modified_by_id_493fb4b1_fk_users_user_id";
SET CONSTRAINTS "flows_flowlabel_created_by_id_9a7b3325_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flowlabel" DROP CONSTRAINT "flows_flowlabel_created_by_id_9a7b3325_fk_users_user_id";
SET CONSTRAINTS "flows_flowlabel_modified_by_id_84e574e7_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flowlabel" DROP CONSTRAINT "flows_flowlabel_modified_by_id_84e574e7_fk_users_user_id";
SET CONSTRAINTS "locations_boundaryalias_created_by_id_46911c69_fk_users_user_id" IMMEDIATE; ALTER TABLE "locations_boundaryalias" DROP CONSTRAINT "locations_boundaryalias_created_by_id_46911c69_fk_users_user_id";
SET CONSTRAINTS "locations_boundaryal_modified_by_id_fabf1a13_fk_users_use" IMMEDIATE; ALTER TABLE "locations_boundaryalias" DROP CONSTRAINT "locations_boundaryal_modified_by_id_fabf1a13_fk_users_use";
SET CONSTRAINTS "tickets_ticket_opened_by_id_dc986186_fk_users_user_id" IMMEDIATE; ALTER TABLE "tickets_ticket" DROP CONSTRAINT "tickets_ticket_opened_by_id_dc986186_fk_users_user_id";
SET CONSTRAINTS "orgs_orgmembership_user_id_ebcaadcf_fk_users_user_id" IMMEDIATE; ALTER TABLE "orgs_orgmembership" DROP CONSTRAINT "orgs_orgmembership_user_id_ebcaadcf_fk_users_user_id";
SET CONSTRAINTS "orgs_invitation_created_by_id_147e359a_fk_users_user_id" IMMEDIATE; ALTER TABLE "orgs_invitation" DROP CONSTRAINT "orgs_invitation_created_by_id_147e359a_fk_users_user_id";
SET CONSTRAINTS "orgs_invitation_modified_by_id_dd8cae65_fk_users_user_id" IMMEDIATE; ALTER TABLE "orgs_invitation" DROP CONSTRAINT "orgs_invitation_modified_by_id_dd8cae65_fk_users_user_id";
SET CONSTRAINTS "orgs_org_created_by_id_f738c068_fk_users_user_id" IMMEDIATE; ALTER TABLE "orgs_org" DROP CONSTRAINT "orgs_org_created_by_id_f738c068_fk_users_user_id";
SET CONSTRAINTS "orgs_org_modified_by_id_61e424e7_fk_users_user_id" IMMEDIATE; ALTER TABLE "orgs_org" DROP CONSTRAINT "orgs_org_modified_by_id_61e424e7_fk_users_user_id";
SET CONSTRAINTS "orgs_orgimport_created_by_id_65e458cc_fk_users_user_id" IMMEDIATE; ALTER TABLE "orgs_orgimport" DROP CONSTRAINT "orgs_orgimport_created_by_id_65e458cc_fk_users_user_id";
SET CONSTRAINTS "orgs_orgimport_modified_by_id_f75b5407_fk_users_user_id" IMMEDIATE; ALTER TABLE "orgs_orgimport" DROP CONSTRAINT "orgs_orgimport_modified_by_id_f75b5407_fk_users_user_id";
SET CONSTRAINTS "flows_flowrevision_created_by_id_fb31d40f_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flowrevision" DROP CONSTRAINT "flows_flowrevision_created_by_id_fb31d40f_fk_users_user_id";
SET CONSTRAINTS "tickets_shortcut_created_by_id_580d144c_fk_users_user_id" IMMEDIATE; ALTER TABLE "tickets_shortcut" DROP CONSTRAINT "tickets_shortcut_created_by_id_580d144c_fk_users_user_id";
SET CONSTRAINTS "tickets_shortcut_modified_by_id_6276867a_fk_users_user_id" IMMEDIATE; ALTER TABLE "tickets_shortcut" DROP CONSTRAINT "tickets_shortcut_modified_by_id_6276867a_fk_users_user_id";
SET CONSTRAINTS "tickets_team_created_by_id_6e92ba12_fk_users_user_id" IMMEDIATE; ALTER TABLE "tickets_team" DROP CONSTRAINT "tickets_team_created_by_id_6e92ba12_fk_users_user_id";
SET CONSTRAINTS "tickets_team_modified_by_id_99a64cad_fk_users_user_id" IMMEDIATE; ALTER TABLE "tickets_team" DROP CONSTRAINT "tickets_team_modified_by_id_99a64cad_fk_users_user_id";
SET CONSTRAINTS "tickets_topic_created_by_id_a7daf971_fk_users_user_id" IMMEDIATE; ALTER TABLE "tickets_topic" DROP CONSTRAINT "tickets_topic_created_by_id_a7daf971_fk_users_user_id";
SET CONSTRAINTS "tickets_topic_modified_by_id_409a6eb0_fk_users_user_id" IMMEDIATE; ALTER TABLE "tickets_topic" DROP CONSTRAINT "tickets_topic_modified_by_id_409a6eb0_fk_users_user_id";
ALTER TABLE "users_user" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "users_user_id_seq" AS bigint;
ALTER TABLE "flows_flowstart" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "flows_flowstart" ALTER COLUMN "modified_by_id" TYPE bigint USING "modified_by_id"::bigint;
ALTER TABLE "flows_flow_user_dependencies" ALTER COLUMN "user_id" TYPE bigint USING "user_id"::bigint;
ALTER TABLE "users_user_groups" ALTER COLUMN "user_id" TYPE bigint USING "user_id"::bigint;
ALTER TABLE "users_user_user_permissions" ALTER COLUMN "user_id" TYPE bigint USING "user_id"::bigint;
ALTER TABLE "ai_llm" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "ai_llm" ALTER COLUMN "modified_by_id" TYPE bigint USING "modified_by_id"::bigint;
ALTER TABLE "tickets_ticket" ALTER COLUMN "assignee_id" TYPE bigint USING "assignee_id"::bigint;
ALTER TABLE "channels_channel" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "channels_channel" ALTER COLUMN "modified_by_id" TYPE bigint USING "modified_by_id"::bigint;
ALTER TABLE "contacts_contactnote" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "contacts_contactfield" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "contacts_contactfield" ALTER COLUMN "modified_by_id" TYPE bigint USING "modified_by_id"::bigint;
ALTER TABLE "contacts_contactgroup" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "contacts_contactgroup" ALTER COLUMN "modified_by_id" TYPE bigint USING "modified_by_id"::bigint;
ALTER TABLE "contacts_contactimport" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "contacts_contactimport" ALTER COLUMN "modified_by_id" TYPE bigint USING "modified_by_id"::bigint;
ALTER TABLE "orgs_export" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "flows_flow" ALTER COLUMN "saved_by_id" TYPE bigint USING "saved_by_id"::bigint;
ALTER TABLE "flows_flow" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "flows_flow" ALTER COLUMN "modified_by_id" TYPE bigint USING "modified_by_id"::bigint;
ALTER TABLE "flows_flowlabel" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "flows_flowlabel" ALTER COLUMN "modified_by_id" TYPE bigint USING "modified_by_id"::bigint;
ALTER TABLE "locations_boundaryalias" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "locations_boundaryalias" ALTER COLUMN "modified_by_id" TYPE bigint USING "modified_by_id"::bigint;
ALTER TABLE "tickets_ticket" ALTER COLUMN "opened_by_id" TYPE bigint USING "opened_by_id"::bigint;
ALTER TABLE "orgs_orgmembership" ALTER COLUMN "user_id" TYPE bigint USING "user_id"::bigint;
ALTER TABLE "orgs_invitation" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "orgs_invitation" ALTER COLUMN "modified_by_id" TYPE bigint USING "modified_by_id"::bigint;
ALTER TABLE "orgs_org" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "orgs_org" ALTER COLUMN "modified_by_id" TYPE bigint USING "modified_by_id"::bigint;
ALTER TABLE "orgs_orgimport" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "orgs_orgimport" ALTER COLUMN "modified_by_id" TYPE bigint USING "modified_by_id"::bigint;
ALTER TABLE "flows_flowrevision" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "tickets_shortcut" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "tickets_shortcut" ALTER COLUMN "modified_by_id" TYPE bigint USING "modified_by_id"::bigint;
ALTER TABLE "tickets_team" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "tickets_team" ALTER COLUMN "modified_by_id" TYPE bigint USING "modified_by_id"::bigint;
ALTER TABLE "tickets_topic" ALTER COLUMN "created_by_id" TYPE bigint USING "created_by_id"::bigint;
ALTER TABLE "tickets_topic" ALTER COLUMN "modified_by_id" TYPE bigint USING "modified_by_id"::bigint;
ALTER TABLE "contacts_contact" ADD CONSTRAINT "contacts_contact_created_by_id_57537352_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contact" ADD CONSTRAINT "contacts_contact_modified_by_id_db5cbe12_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowstart" ADD CONSTRAINT "flows_flowstart_created_by_id_4eb88868_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowstart" ADD CONSTRAINT "flows_flowstart_modified_by_id_c9a338d3_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_user_dependencies" ADD CONSTRAINT "flows_flow_user_dependencies_user_id_9201056c_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_user_id_5f6f5a90_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_permissions_user_id_20aca447_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ai_llm" ADD CONSTRAINT "ai_llm_created_by_id_b141546f_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ai_llm" ADD CONSTRAINT "ai_llm_modified_by_id_138573f7_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_ticket" ADD CONSTRAINT "tickets_ticket_assignee_id_3a5aa407_fk_users_user_id" FOREIGN KEY ("assignee_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "channels_channel" ADD CONSTRAINT "channels_channel_created_by_id_8141adf4_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "channels_channel" ADD CONSTRAINT "channels_channel_modified_by_id_af6bcc5e_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactnote" ADD CONSTRAINT "contacts_contactnote_created_by_id_1d4def0c_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactfield" ADD CONSTRAINT "contacts_contactfield_created_by_id_7bce7fd0_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactfield" ADD CONSTRAINT "contacts_contactfield_modified_by_id_99cfac9b_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactgroup" ADD CONSTRAINT "contacts_contactgroup_created_by_id_6bbeef89_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactgroup" ADD CONSTRAINT "contacts_contactgroup_modified_by_id_a765a76e_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactimport" ADD CONSTRAINT "contacts_contactimport_created_by_id_a34024c3_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactimport" ADD CONSTRAINT "contacts_contactimport_modified_by_id_6cf6a8d5_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_export" ADD CONSTRAINT "orgs_export_created_by_id_c83cb736_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow" ADD CONSTRAINT "flows_flow_saved_by_id_edb563b6_fk_users_user_id" FOREIGN KEY ("saved_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow" ADD CONSTRAINT "flows_flow_created_by_id_2e1adcb6_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow" ADD CONSTRAINT "flows_flow_modified_by_id_493fb4b1_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowlabel" ADD CONSTRAINT "flows_flowlabel_created_by_id_9a7b3325_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowlabel" ADD CONSTRAINT "flows_flowlabel_modified_by_id_84e574e7_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "locations_boundaryalias" ADD CONSTRAINT "locations_boundaryalias_created_by_id_46911c69_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "locations_boundaryalias" ADD CONSTRAINT "locations_boundaryal_modified_by_id_fabf1a13_fk_users_use" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_ticket" ADD CONSTRAINT "tickets_ticket_opened_by_id_dc986186_fk_users_user_id" FOREIGN KEY ("opened_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_orgmembership" ADD CONSTRAINT "orgs_orgmembership_user_id_ebcaadcf_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_invitation" ADD CONSTRAINT "orgs_invitation_created_by_id_147e359a_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_invitation" ADD CONSTRAINT "orgs_invitation_modified_by_id_dd8cae65_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_org" ADD CONSTRAINT "orgs_org_created_by_id_f738c068_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_org" ADD CONSTRAINT "orgs_org_modified_by_id_61e424e7_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_orgimport" ADD CONSTRAINT "orgs_orgimport_created_by_id_65e458cc_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_orgimport" ADD CONSTRAINT "orgs_orgimport_modified_by_id_f75b5407_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowrevision" ADD CONSTRAINT "flows_flowrevision_created_by_id_fb31d40f_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_shortcut" ADD CONSTRAINT "tickets_shortcut_created_by_id_580d144c_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_shortcut" ADD CONSTRAINT "tickets_shortcut_modified_by_id_6276867a_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_team" ADD CONSTRAINT "tickets_team_created_by_id_6e92ba12_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_team" ADD CONSTRAINT "tickets_team_modified_by_id_99a64cad_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_topic" ADD CONSTRAINT "tickets_topic_created_by_id_a7daf971_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_topic" ADD CONSTRAINT "tickets_topic_modified_by_id_409a6eb0_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
"""

REVERSE_SQL = """
--
-- Alter field id on user
--
SET CONSTRAINTS "contacts_contact_created_by_id_57537352_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contact" DROP CONSTRAINT "contacts_contact_created_by_id_57537352_fk_users_user_id";
SET CONSTRAINTS "contacts_contact_modified_by_id_db5cbe12_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contact" DROP CONSTRAINT "contacts_contact_modified_by_id_db5cbe12_fk_users_user_id";
SET CONSTRAINTS "flows_flowstart_created_by_id_4eb88868_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flowstart" DROP CONSTRAINT "flows_flowstart_created_by_id_4eb88868_fk_users_user_id";
SET CONSTRAINTS "flows_flowstart_modified_by_id_c9a338d3_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flowstart" DROP CONSTRAINT "flows_flowstart_modified_by_id_c9a338d3_fk_users_user_id";
SET CONSTRAINTS "flows_flow_user_dependencies_user_id_9201056c_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flow_user_dependencies" DROP CONSTRAINT "flows_flow_user_dependencies_user_id_9201056c_fk_users_user_id";
SET CONSTRAINTS "users_user_groups_user_id_5f6f5a90_fk_users_user_id" IMMEDIATE; ALTER TABLE "users_user_groups" DROP CONSTRAINT "users_user_groups_user_id_5f6f5a90_fk_users_user_id";
SET CONSTRAINTS "users_user_user_permissions_user_id_20aca447_fk_users_user_id" IMMEDIATE; ALTER TABLE "users_user_user_permissions" DROP CONSTRAINT "users_user_user_permissions_user_id_20aca447_fk_users_user_id";
SET CONSTRAINTS "ai_llm_created_by_id_b141546f_fk_users_user_id" IMMEDIATE; ALTER TABLE "ai_llm" DROP CONSTRAINT "ai_llm_created_by_id_b141546f_fk_users_user_id";
SET CONSTRAINTS "ai_llm_modified_by_id_138573f7_fk_users_user_id" IMMEDIATE; ALTER TABLE "ai_llm" DROP CONSTRAINT "ai_llm_modified_by_id_138573f7_fk_users_user_id";
SET CONSTRAINTS "tickets_ticket_assignee_id_3a5aa407_fk_users_user_id" IMMEDIATE; ALTER TABLE "tickets_ticket" DROP CONSTRAINT "tickets_ticket_assignee_id_3a5aa407_fk_users_user_id";
SET CONSTRAINTS "channels_channel_created_by_id_8141adf4_fk_users_user_id" IMMEDIATE; ALTER TABLE "channels_channel" DROP CONSTRAINT "channels_channel_created_by_id_8141adf4_fk_users_user_id";
SET CONSTRAINTS "channels_channel_modified_by_id_af6bcc5e_fk_users_user_id" IMMEDIATE; ALTER TABLE "channels_channel" DROP CONSTRAINT "channels_channel_modified_by_id_af6bcc5e_fk_users_user_id";
SET CONSTRAINTS "contacts_contactnote_created_by_id_1d4def0c_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contactnote" DROP CONSTRAINT "contacts_contactnote_created_by_id_1d4def0c_fk_users_user_id";
SET CONSTRAINTS "contacts_contactfield_created_by_id_7bce7fd0_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contactfield" DROP CONSTRAINT "contacts_contactfield_created_by_id_7bce7fd0_fk_users_user_id";
SET CONSTRAINTS "contacts_contactfield_modified_by_id_99cfac9b_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contactfield" DROP CONSTRAINT "contacts_contactfield_modified_by_id_99cfac9b_fk_users_user_id";
SET CONSTRAINTS "contacts_contactgroup_created_by_id_6bbeef89_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contactgroup" DROP CONSTRAINT "contacts_contactgroup_created_by_id_6bbeef89_fk_users_user_id";
SET CONSTRAINTS "contacts_contactgroup_modified_by_id_a765a76e_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contactgroup" DROP CONSTRAINT "contacts_contactgroup_modified_by_id_a765a76e_fk_users_user_id";
SET CONSTRAINTS "contacts_contactimport_created_by_id_a34024c3_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contactimport" DROP CONSTRAINT "contacts_contactimport_created_by_id_a34024c3_fk_users_user_id";
SET CONSTRAINTS "contacts_contactimport_modified_by_id_6cf6a8d5_fk_users_user_id" IMMEDIATE; ALTER TABLE "contacts_contactimport" DROP CONSTRAINT "contacts_contactimport_modified_by_id_6cf6a8d5_fk_users_user_id";
SET CONSTRAINTS "orgs_export_created_by_id_c83cb736_fk_users_user_id" IMMEDIATE; ALTER TABLE "orgs_export" DROP CONSTRAINT "orgs_export_created_by_id_c83cb736_fk_users_user_id";
SET CONSTRAINTS "flows_flow_saved_by_id_edb563b6_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flow" DROP CONSTRAINT "flows_flow_saved_by_id_edb563b6_fk_users_user_id";
SET CONSTRAINTS "flows_flow_created_by_id_2e1adcb6_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flow" DROP CONSTRAINT "flows_flow_created_by_id_2e1adcb6_fk_users_user_id";
SET CONSTRAINTS "flows_flow_modified_by_id_493fb4b1_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flow" DROP CONSTRAINT "flows_flow_modified_by_id_493fb4b1_fk_users_user_id";
SET CONSTRAINTS "flows_flowlabel_created_by_id_9a7b3325_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flowlabel" DROP CONSTRAINT "flows_flowlabel_created_by_id_9a7b3325_fk_users_user_id";
SET CONSTRAINTS "flows_flowlabel_modified_by_id_84e574e7_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flowlabel" DROP CONSTRAINT "flows_flowlabel_modified_by_id_84e574e7_fk_users_user_id";
SET CONSTRAINTS "locations_boundaryalias_created_by_id_46911c69_fk_users_user_id" IMMEDIATE; ALTER TABLE "locations_boundaryalias" DROP CONSTRAINT "locations_boundaryalias_created_by_id_46911c69_fk_users_user_id";
SET CONSTRAINTS "locations_boundaryal_modified_by_id_fabf1a13_fk_users_use" IMMEDIATE; ALTER TABLE "locations_boundaryalias" DROP CONSTRAINT "locations_boundaryal_modified_by_id_fabf1a13_fk_users_use";
SET CONSTRAINTS "tickets_ticket_opened_by_id_dc986186_fk_users_user_id" IMMEDIATE; ALTER TABLE "tickets_ticket" DROP CONSTRAINT "tickets_ticket_opened_by_id_dc986186_fk_users_user_id";
SET CONSTRAINTS "orgs_orgmembership_user_id_ebcaadcf_fk_users_user_id" IMMEDIATE; ALTER TABLE "orgs_orgmembership" DROP CONSTRAINT "orgs_orgmembership_user_id_ebcaadcf_fk_users_user_id";
SET CONSTRAINTS "orgs_invitation_created_by_id_147e359a_fk_users_user_id" IMMEDIATE; ALTER TABLE "orgs_invitation" DROP CONSTRAINT "orgs_invitation_created_by_id_147e359a_fk_users_user_id";
SET CONSTRAINTS "orgs_invitation_modified_by_id_dd8cae65_fk_users_user_id" IMMEDIATE; ALTER TABLE "orgs_invitation" DROP CONSTRAINT "orgs_invitation_modified_by_id_dd8cae65_fk_users_user_id";
SET CONSTRAINTS "orgs_org_created_by_id_f738c068_fk_users_user_id" IMMEDIATE; ALTER TABLE "orgs_org" DROP CONSTRAINT "orgs_org_created_by_id_f738c068_fk_users_user_id";
SET CONSTRAINTS "orgs_org_modified_by_id_61e424e7_fk_users_user_id" IMMEDIATE; ALTER TABLE "orgs_org" DROP CONSTRAINT "orgs_org_modified_by_id_61e424e7_fk_users_user_id";
SET CONSTRAINTS "orgs_orgimport_created_by_id_65e458cc_fk_users_user_id" IMMEDIATE; ALTER TABLE "orgs_orgimport" DROP CONSTRAINT "orgs_orgimport_created_by_id_65e458cc_fk_users_user_id";
SET CONSTRAINTS "orgs_orgimport_modified_by_id_f75b5407_fk_users_user_id" IMMEDIATE; ALTER TABLE "orgs_orgimport" DROP CONSTRAINT "orgs_orgimport_modified_by_id_f75b5407_fk_users_user_id";
SET CONSTRAINTS "flows_flowrevision_created_by_id_fb31d40f_fk_users_user_id" IMMEDIATE; ALTER TABLE "flows_flowrevision" DROP CONSTRAINT "flows_flowrevision_created_by_id_fb31d40f_fk_users_user_id";
SET CONSTRAINTS "tickets_shortcut_created_by_id_580d144c_fk_users_user_id" IMMEDIATE; ALTER TABLE "tickets_shortcut" DROP CONSTRAINT "tickets_shortcut_created_by_id_580d144c_fk_users_user_id";
SET CONSTRAINTS "tickets_shortcut_modified_by_id_6276867a_fk_users_user_id" IMMEDIATE; ALTER TABLE "tickets_shortcut" DROP CONSTRAINT "tickets_shortcut_modified_by_id_6276867a_fk_users_user_id";
SET CONSTRAINTS "tickets_team_created_by_id_6e92ba12_fk_users_user_id" IMMEDIATE; ALTER TABLE "tickets_team" DROP CONSTRAINT "tickets_team_created_by_id_6e92ba12_fk_users_user_id";
SET CONSTRAINTS "tickets_team_modified_by_id_99a64cad_fk_users_user_id" IMMEDIATE; ALTER TABLE "tickets_team" DROP CONSTRAINT "tickets_team_modified_by_id_99a64cad_fk_users_user_id";
SET CONSTRAINTS "tickets_topic_created_by_id_a7daf971_fk_users_user_id" IMMEDIATE; ALTER TABLE "tickets_topic" DROP CONSTRAINT "tickets_topic_created_by_id_a7daf971_fk_users_user_id";
SET CONSTRAINTS "tickets_topic_modified_by_id_409a6eb0_fk_users_user_id" IMMEDIATE; ALTER TABLE "tickets_topic" DROP CONSTRAINT "tickets_topic_modified_by_id_409a6eb0_fk_users_user_id";
ALTER TABLE "users_user" ALTER COLUMN "id" TYPE integer USING "id"::integer;
ALTER SEQUENCE IF EXISTS "users_user_id_seq" AS integer;
ALTER TABLE "flows_flowstart" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "flows_flowstart" ALTER COLUMN "modified_by_id" TYPE integer USING "modified_by_id"::integer;
ALTER TABLE "flows_flow_user_dependencies" ALTER COLUMN "user_id" TYPE integer USING "user_id"::integer;
ALTER TABLE "users_user_groups" ALTER COLUMN "user_id" TYPE integer USING "user_id"::integer;
ALTER TABLE "users_user_user_permissions" ALTER COLUMN "user_id" TYPE integer USING "user_id"::integer;
ALTER TABLE "ai_llm" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "ai_llm" ALTER COLUMN "modified_by_id" TYPE integer USING "modified_by_id"::integer;
ALTER TABLE "tickets_ticket" ALTER COLUMN "assignee_id" TYPE integer USING "assignee_id"::integer;
ALTER TABLE "channels_channel" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "channels_channel" ALTER COLUMN "modified_by_id" TYPE integer USING "modified_by_id"::integer;
ALTER TABLE "contacts_contactnote" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "contacts_contactfield" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "contacts_contactfield" ALTER COLUMN "modified_by_id" TYPE integer USING "modified_by_id"::integer;
ALTER TABLE "contacts_contactgroup" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "contacts_contactgroup" ALTER COLUMN "modified_by_id" TYPE integer USING "modified_by_id"::integer;
ALTER TABLE "contacts_contactimport" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "contacts_contactimport" ALTER COLUMN "modified_by_id" TYPE integer USING "modified_by_id"::integer;
ALTER TABLE "orgs_export" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "flows_flow" ALTER COLUMN "saved_by_id" TYPE integer USING "saved_by_id"::integer;
ALTER TABLE "flows_flow" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "flows_flow" ALTER COLUMN "modified_by_id" TYPE integer USING "modified_by_id"::integer;
ALTER TABLE "flows_flowlabel" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "flows_flowlabel" ALTER COLUMN "modified_by_id" TYPE integer USING "modified_by_id"::integer;
ALTER TABLE "locations_boundaryalias" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "locations_boundaryalias" ALTER COLUMN "modified_by_id" TYPE integer USING "modified_by_id"::integer;
ALTER TABLE "tickets_ticket" ALTER COLUMN "opened_by_id" TYPE integer USING "opened_by_id"::integer;
ALTER TABLE "orgs_orgmembership" ALTER COLUMN "user_id" TYPE integer USING "user_id"::integer;
ALTER TABLE "orgs_invitation" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "orgs_invitation" ALTER COLUMN "modified_by_id" TYPE integer USING "modified_by_id"::integer;
ALTER TABLE "orgs_org" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "orgs_org" ALTER COLUMN "modified_by_id" TYPE integer USING "modified_by_id"::integer;
ALTER TABLE "orgs_orgimport" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "orgs_orgimport" ALTER COLUMN "modified_by_id" TYPE integer USING "modified_by_id"::integer;
ALTER TABLE "flows_flowrevision" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "tickets_shortcut" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "tickets_shortcut" ALTER COLUMN "modified_by_id" TYPE integer USING "modified_by_id"::integer;
ALTER TABLE "tickets_team" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "tickets_team" ALTER COLUMN "modified_by_id" TYPE integer USING "modified_by_id"::integer;
ALTER TABLE "tickets_topic" ALTER COLUMN "created_by_id" TYPE integer USING "created_by_id"::integer;
ALTER TABLE "tickets_topic" ALTER COLUMN "modified_by_id" TYPE integer USING "modified_by_id"::integer;
ALTER TABLE "contacts_contact" ADD CONSTRAINT "contacts_contact_created_by_id_57537352_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contact" ADD CONSTRAINT "contacts_contact_modified_by_id_db5cbe12_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowstart" ADD CONSTRAINT "flows_flowstart_created_by_id_4eb88868_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowstart" ADD CONSTRAINT "flows_flowstart_modified_by_id_c9a338d3_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_user_dependencies" ADD CONSTRAINT "flows_flow_user_dependencies_user_id_9201056c_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_user_id_5f6f5a90_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_permissions_user_id_20aca447_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ai_llm" ADD CONSTRAINT "ai_llm_created_by_id_b141546f_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ai_llm" ADD CONSTRAINT "ai_llm_modified_by_id_138573f7_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_ticket" ADD CONSTRAINT "tickets_ticket_assignee_id_3a5aa407_fk_users_user_id" FOREIGN KEY ("assignee_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "channels_channel" ADD CONSTRAINT "channels_channel_created_by_id_8141adf4_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "channels_channel" ADD CONSTRAINT "channels_channel_modified_by_id_af6bcc5e_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactnote" ADD CONSTRAINT "contacts_contactnote_created_by_id_1d4def0c_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactfield" ADD CONSTRAINT "contacts_contactfield_created_by_id_7bce7fd0_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactfield" ADD CONSTRAINT "contacts_contactfield_modified_by_id_99cfac9b_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactgroup" ADD CONSTRAINT "contacts_contactgroup_created_by_id_6bbeef89_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactgroup" ADD CONSTRAINT "contacts_contactgroup_modified_by_id_a765a76e_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactimport" ADD CONSTRAINT "contacts_contactimport_created_by_id_a34024c3_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contactimport" ADD CONSTRAINT "contacts_contactimport_modified_by_id_6cf6a8d5_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_export" ADD CONSTRAINT "orgs_export_created_by_id_c83cb736_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow" ADD CONSTRAINT "flows_flow_saved_by_id_edb563b6_fk_users_user_id" FOREIGN KEY ("saved_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow" ADD CONSTRAINT "flows_flow_created_by_id_2e1adcb6_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow" ADD CONSTRAINT "flows_flow_modified_by_id_493fb4b1_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowlabel" ADD CONSTRAINT "flows_flowlabel_created_by_id_9a7b3325_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowlabel" ADD CONSTRAINT "flows_flowlabel_modified_by_id_84e574e7_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "locations_boundaryalias" ADD CONSTRAINT "locations_boundaryalias_created_by_id_46911c69_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "locations_boundaryalias" ADD CONSTRAINT "locations_boundaryal_modified_by_id_fabf1a13_fk_users_use" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_ticket" ADD CONSTRAINT "tickets_ticket_opened_by_id_dc986186_fk_users_user_id" FOREIGN KEY ("opened_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_orgmembership" ADD CONSTRAINT "orgs_orgmembership_user_id_ebcaadcf_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_invitation" ADD CONSTRAINT "orgs_invitation_created_by_id_147e359a_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_invitation" ADD CONSTRAINT "orgs_invitation_modified_by_id_dd8cae65_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_org" ADD CONSTRAINT "orgs_org_created_by_id_f738c068_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_org" ADD CONSTRAINT "orgs_org_modified_by_id_61e424e7_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_orgimport" ADD CONSTRAINT "orgs_orgimport_created_by_id_65e458cc_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orgs_orgimport" ADD CONSTRAINT "orgs_orgimport_modified_by_id_f75b5407_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowrevision" ADD CONSTRAINT "flows_flowrevision_created_by_id_fb31d40f_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_shortcut" ADD CONSTRAINT "tickets_shortcut_created_by_id_580d144c_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_shortcut" ADD CONSTRAINT "tickets_shortcut_modified_by_id_6276867a_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_team" ADD CONSTRAINT "tickets_team_created_by_id_6e92ba12_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_team" ADD CONSTRAINT "tickets_team_modified_by_id_99a64cad_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_topic" ADD CONSTRAINT "tickets_topic_created_by_id_a7daf971_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets_topic" ADD CONSTRAINT "tickets_topic_modified_by_id_409a6eb0_fk_users_user_id" FOREIGN KEY ("modified_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_user_settings"),
        # so unapplying doesn't try to alter FKs on the dropped tables
        ("classifiers", "0018_delete_classifier_intent"),
        ("tickets", "0087_delete_ticketevent"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="user",
                    name="id",
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
            ],
            database_operations=[migrations.RunSQL(FORWARD_SQL, reverse_sql=REVERSE_SQL)],
        ),
    ]
