# Generated by Django 6.0.7 on 2026-07-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_user_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("en-us", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("pt-br", "Portuguese"),
                ],
                default="en-us",
                max_length=8,
            ),
        ),
    ]
