# Generated by Django 6.0.7 on 2026-07-30 15:51

from django.db import migrations

# website languages still supported at the time of this migration
LANGUAGES = ["en-us", "es", "fr", "pt-br"]
DEFAULT_LANGUAGE = "en-us"


def reset_dropped_languages(apps, schema_editor):
    User = apps.get_model("users", "User")

    num_updated = User.objects.exclude(language__in=LANGUAGES).update(language=DEFAULT_LANGUAGE)
    if num_updated:
        print(f"Updated {num_updated} users with an unsupported language to {DEFAULT_LANGUAGE}")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    reset_dropped_languages(apps, None)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_alter_user_language"),
    ]

    operations = [
        migrations.RunPython(reset_dropped_languages, migrations.RunPython.noop),
    ]
