# Generated by Django 2.0.9 on 2018-10-30 09:33

from django.db import migrations

CREATE_INDEX = """
    CREATE INDEX IF NOT EXISTS channels_channelsession_failed_events
    ON channels_channelsession (modified_on ASC NULLS LAST) WHERE status IN ('F', 'N', 'B') and direction = 'O' and is_active = True;
"""


class Migration(migrations.Migration):

    dependencies = [("channels", "0104_auto_20181024_0959")]

    operations = [migrations.RunSQL(CREATE_INDEX)]
