# Generated by Django 2.2.4 on 2020-02-29 16:45

from django.db import migrations

# language=SQL
INDEX_SQL_SYNC_EVENT_CREATED_ON = """
CREATE INDEX IF NOT EXISTS channels_syncevent_created_on_desc
  on channels_syncevent (created_on DESC);
"""


class Migration(migrations.Migration):

    dependencies = [("channels", "0122_populate_allow_international")]

    operations = [migrations.RunSQL(INDEX_SQL_SYNC_EVENT_CREATED_ON)]
