# Generated by Django 5.1.4 on 2025-04-02 16:04

from django.db import migrations


def populate_max_concurrent_calls(apps, schema_editor):  # pragma: no cover
    Channel = apps.get_model("channels", "Channel")

    channels = Channel.objects.filter(config__max_concurrent_events__isnull=False)
    for channel in channels:
        channel.config["max_concurrent_calls"] = channel.config["max_concurrent_events"]
        channel.save(update_fields=("config",))


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0193_channel_is_enabled"),
    ]

    operations = [
        migrations.RunPython(populate_max_concurrent_calls, migrations.RunPython.noop),
    ]
