# Generated by Django 5.2.1 on 2025-06-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0201_backfill_channelcount_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelcount",
            name="count_type",
            field=models.CharField(null=True),
        ),
    ]
