# Generated by Django 5.2 on 2026-03-31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0209_alter_channelcount_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="log_policy",
        ),
    ]
