# Generated by Django 5.2.12 on 2026-03-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0209_alter_channelcount_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="is_allowed",
            field=models.BooleanField(default=True),
        ),
    ]
