# Generated by Django 6.0.7 on 2026-07-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0211_alter_syncevent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelevent",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
