# Generated by Django 6.0.7 on 2026-07-31 16:31

from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0212_alter_channelevent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, unique=True),
        ),
    ]
