# Generated by Django 6.0.7 on 2026-08-11 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0213_alter_channel_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channelevent",
            name="optin",
        ),
    ]
