# Generated by Django 6.0.7 on 2026-08-12 09:00

from django.db import migrations
from django.utils import timezone

# the channel types whose sending/receiving is handled by courier's legacy WhatsApp handlers
LEGACY_TYPES = ("WA", "D3", "TXW")


def release_legacy_whatsapp_channels(apps, schema_editor):
    Channel = apps.get_model("channels", "Channel")
    Trigger = apps.get_model("triggers", "Trigger")
    Incident = apps.get_model("notifications", "Incident")
    Template = apps.get_model("templates", "Template")
    TemplateTranslation = apps.get_model("templates", "TemplateTranslation")

    channels = list(Channel.objects.filter(channel_type__in=LEGACY_TYPES, is_active=True))

    # archive and release any triggers for these channels
    num_triggers = Trigger.objects.filter(channel__in=channels, is_active=True).update(
        is_active=False, is_archived=True, modified_on=timezone.now()
    )

    # end any open incidents for these channels
    num_incidents = Incident.objects.filter(channel__in=channels, ended_on=None).update(ended_on=timezone.now())

    # delete any template translations for these channels
    translations = TemplateTranslation.objects.filter(channel__in=channels)
    template_ids = set(translations.values_list("template_id", flat=True))

    # base translations are protected so clear any pointing at translations we're about to delete
    Template.objects.filter(base_translation__channel__in=channels).update(base_translation=None)

    num_translations, _ = translations.delete()

    # any affected template which has lost its base translation needs a new one
    for template in Template.objects.filter(id__in=template_ids, base_translation=None):
        update_base_translation(template)

    # finally make the channels themselves inactive - note that unlike Channel.release we don't try to deactivate them
    # with the provider, or interrupt sessions on them via mailroom
    num_channels = Channel.objects.filter(id__in=[c.id for c in channels]).update(
        is_active=False, modified_on=timezone.now()
    )

    if num_channels:
        print(
            f"Released {num_channels} legacy WhatsApp channels ({num_triggers} triggers, {num_incidents} incidents, "
            f"{num_translations} template translations)"
        )


def update_base_translation(template):
    """
    Version of Template.update_base for historical models - tries to set a new base translation for this template.
    """
    candidates = template.translations.all()

    # try to find one in the org's primary language, otherwise fallback to the oldest
    languages = template.org.flow_languages
    new_base = candidates.filter(locale__startswith=languages[0]).first() if languages else None
    if not new_base:
        new_base = candidates.order_by("id").first()

    if new_base:
        template.base_translation = new_base
        template.modified_on = timezone.now()
        template.save(update_fields=("base_translation", "modified_on"))

        # update remaining translations' compatibility with the new base variable list
        for trans in candidates:
            trans.is_compatible = trans.variables == new_base.variables
            trans.save(update_fields=("is_compatible",))


def apply_manual():  # pragma: no cover
    from django.apps import apps

    release_legacy_whatsapp_channels(apps, None)


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0214_remove_channelevent_optin"),
        ("notifications", "0035_squashed"),
        ("templates", "0049_alter_template_id"),
        ("triggers", "0046_release_optin_triggers"),
    ]

    operations = [
        migrations.RunPython(release_legacy_whatsapp_channels, migrations.RunPython.noop),
    ]
