# Generated by Django 3.2.8 on 2021-10-28 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0088_auto_20210715_1825"),
        ("msgs", "0157_auto_20211028_1300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="msg",
            name="created_on",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="msg",
            name="external_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="msg",
            name="response_to",
            field=models.ForeignKey(
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responses",
                to="msgs.msg",
            ),
        ),
        migrations.AlterField(
            model_name="msg",
            name="status",
            field=models.CharField(
                choices=[
                    ("I", "Initializing"),
                    ("P", "Pending"),
                    ("Q", "Queued"),
                    ("W", "Wired"),
                    ("S", "Sent"),
                    ("D", "Delivered"),
                    ("H", "Handled"),
                    ("E", "Error"),
                    ("F", "Failed"),
                    ("R", "Resent"),
                ],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="msg",
            name="topup",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="msgs", to="orgs.topup"
            ),
        ),
    ]
