# Generated by Django 4.0.7 on 2022-10-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0192_broadcastcrudl"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BroadcastCRUDL",
        ),
    ]
