# Generated by Django 4.0.9 on 2023-02-21 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0220_alter_msg_msg_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="msg",
            name="msgs_outgoing_to_retry",
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="msg",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("H", "Handled"),
                    ("I", "Initializing"),
                    ("Q", "Queued"),
                    ("W", "Wired"),
                    ("S", "Sent"),
                    ("D", "Delivered"),
                    ("E", "Error"),
                    ("F", "Failed"),
                ],
                db_index=True,
                default="P",
                max_length=1,
            ),
        ),
        migrations.AddIndex(
            model_name="msg",
            index=models.Index(
                condition=models.Q(("direction", "O"), ("next_attempt__isnull", False), ("status__in", ("I", "E"))),
                fields=["next_attempt", "created_on", "id"],
                name="msgs_outgoing_to_retry",
            ),
        ),
    ]
