# Generated by Django 4.0.9 on 2023-02-21 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0220_alter_msg_msg_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
