# Generated by Django 4.0.9 on 2023-02-23 19:39

import django.db.models.expressions
from django.db import migrations, models

SQL = """
DROP INDEX msgs_msg_org_modified_id_where_inbound;
DROP INDEX msgs_msg_visibility_type_created_id_where_inbound;
"""


class Migration(migrations.Migration):

    dependencies = [("msgs", "0223_index_updates_again")]

    operations = [
        migrations.AddIndex(
            model_name="msg",
            index=models.Index(
                condition=models.Q(("direction", "I"), ("status", "H")),
                fields=["org", "-modified_on", "-id"],
                name="msgs_api_incoming",
            ),
        ),
        migrations.AddIndex(
            model_name="msg",
            index=models.Index(
                django.db.models.expressions.F("org"),
                django.db.models.expressions.F("visibility"),
                django.db.models.expressions.RawSQL("flow_id IS NULL", params=()),
                django.db.models.expressions.OrderBy(django.db.models.expressions.F("created_on"), descending=True),
                django.db.models.expressions.OrderBy(django.db.models.expressions.F("id"), descending=True),
                condition=models.Q(("direction", "I")),
                name="msgs_inbox_flows_archived",
            ),
        ),
        migrations.RunSQL(SQL),
    ]
