# Generated by Django 4.1.7 on 2023-04-24 23:15

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class ForeignKeyToIntegerField(Operation):
    reversible = False

    def __init__(self, *, model_name, name, null):
        self.model_name = model_name
        self.name = name
        self.null = null

    def state_forwards(self, app_label, state):
        state.remove_field(app_label, self.model_name, self.name)
        state.add_field(
            app_label,
            self.model_name,
            f"{self.name}_id",
            models.IntegerField(null=self.null),
            preserve_default=False,
        )

    def database_forwards(self, app_label, schema_editor, from_state, to_state):  # pragma: no cover
        to_model = to_state.apps.get_model(app_label, self.model_name)

        constraint_names = schema_editor._constraint_names(to_model, [f"{self.name}_id"], foreign_key=True)
        for constraint_name in constraint_names:
            schema_editor.execute(schema_editor._delete_fk_sql(to_model, constraint_name))

    def describe(self):  # pragma: no cover
        return f"Converts foreign key {self.model_name}.{self.name} to integer field"


class Migration(migrations.Migration):
    dependencies = [("msgs", "0232_msg_ticket")]

    operations = [
        ForeignKeyToIntegerField(model_name="msg", name="ticket", null=True),
    ]
