# Generated by Django 5.1 on 2024-09-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0269_msg_msgs_outgoing_android_to_fail"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="broadcast",
            name="msgs_broadcasts_queued",
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="status",
            field=models.CharField(
                choices=[
                    ("Q", "Queued"),
                    ("P", "Pending"),
                    ("C", "Completed"),
                    ("S", "Sent"),
                    ("F", "Failed"),
                    ("I", "Interrupted"),
                ],
                default="Q",
                max_length=1,
            ),
        ),
    ]
