# Generated by Django 5.1.4 on 2025-03-24 20:15

from django.db import migrations


SQL = """
----------------------------------------------------------------------
-- Determines the item count scope for a broadcast record
----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION temba_broadcast_countscope(_broadcast msgs_broadcast) RETURNS TEXT STABLE AS $$
BEGIN
  IF _broadcast.is_active = TRUE THEN
    IF _broadcast.schedule_id IS NOT NULL THEN
      RETURN 'bcasts:scheduled';
    ELSE
      RETURN 'bcasts:immediate';
    END IF;
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

----------------------------------------------------------------------
-- Handles DELETE statements on ivr_call table
----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION temba_ivrcall_on_delete() RETURNS TRIGGER AS $$
BEGIN
    -- add negative item counts for all rows being deleted
    INSERT INTO orgs_itemcount("org_id", "scope", "count", "is_squashed")
    SELECT org_id, 'calls:all', -count(*), FALSE FROM oldtab GROUP BY 1;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

----------------------------------------------------------------------
-- Handles INSERT statements on ivr_call table
----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION temba_ivrcall_on_insert() RETURNS TRIGGER AS $$
BEGIN
    -- add positive item counts for all rows being inserted
    INSERT INTO orgs_itemcount("org_id", "scope", "count", "is_squashed")
    SELECT org_id, 'calls:all', count(*), FALSE FROM newtab GROUP BY 1;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0286_update_quick_replies"),
    ]

    operations = [
        migrations.RunSQL(SQL),
    ]
