# Generated by Django 5.1.4 on 2025-03-24 23:03

from django.db import migrations


def convert_bcast_and_call_counts(apps, schema_editor):
    # TODO
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0287_update_triggers"),
    ]

    operations = [
        migrations.RunPython(convert_bcast_and_call_counts, migrations.RunPython.noop),
    ]
