# Generated by Django 5.2.2 on 2025-08-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0289_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="msg",
            name="folder",
            field=models.CharField(max_length=1, null=True),
        ),
    ]
