# Generated by Django 5.2.2 on 2025-09-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0294_backfill_bcast_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="msg",
            name="ticket",
        ),
    ]
