# Generated by Django 5.2.9 on 2026-01-07 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0209_alter_channelcount_count"),
        ("contacts", "0214_alter_contactimport_uuid"),
        ("flows", "0398_remove_flowsession_flows_session_has_output_or_url_and_more"),
        ("msgs", "0299_backfill_msg_events"),
        ("orgs", "0178_alter_orgimport_uuid"),
        ("tickets", "0087_delete_ticketevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="msg",
            constraint=models.UniqueConstraint(
                condition=models.Q(("channel__isnull", False), ("direction", "I"), ("external_id__isnull", False)),
                fields=("channel", "external_id"),
                name="unique_incoming_external_id_per_channel",
            ),
        ),
    ]
