# Generated by Django 5.2.10 on 2026-01-19 20:32

from django.db import migrations


def backfill_external_identifier(apps, schema_editor):  # pragma: no cover
    Msg = apps.get_model("msgs", "Msg")

    num_updated = 0

    while True:
        batch = list(Msg.objects.filter(external_id__isnull=False, external_identifier=None).only("external_id")[:1000])
        if not batch:
            break

        for msg in batch:
            msg.external_identifier = msg.external_id
            num_updated += 1

        Msg.objects.bulk_update(batch, ["external_identifier"])
        print(f"Updated {num_updated} msgs with new external_identifier field")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    backfill_external_identifier(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0300_msg_external_identifier_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_external_identifier, migrations.RunPython.noop),
    ]
