# Generated by Django 5.2.10 on 2026-01-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0301_backfill_external_identifier"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="msg",
            name="msgs_by_external_id",
        ),
        migrations.RemoveField(
            model_name="msg",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="msg",
            name="ticket",
        ),
    ]
