# Generated by Django 5.2.10 on 2026-02-04 21:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0302_remove_msg_msgs_by_external_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msg",
            name="quick_replies",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=150), null=True, size=None
            ),
        ),
    ]
