# Generated by Django 5.2.10 on 2026-02-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0302_remove_msg_msgs_by_external_id_and_more"),
    ]

    operations = [
        # this was a failed attempt to increase the size of quick_replies field
    ]
