# Generated by Django 5.2.10 on 2026-02-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0303_alter_msg_quick_replies"),
    ]

    operations = [
        migrations.AddField(
            model_name="msg",
            name="quickreplies",
            field=models.JSONField(null=True),
        ),
    ]
