# Generated by Django 5.2.10 on 2026-02-10 00:00

from django.db import migrations


def backfill_msg_quickreplies(apps, schema_editor):  # pragma: no cover
    Msg = apps.get_model("msgs", "Msg")

    num_updated = 0

    while True:
        batch = list(
            Msg.objects.filter(quick_replies__isnull=False, quickreplies__isnull=True).exclude(quick_replies=[])[:1000]
        )
        if not batch:
            break

        for msg in batch:
            qrs = []
            for qr in msg.quick_replies:
                if qr.startswith("<location>"):
                    text = qr[10:] or None
                    d = {"type": "location"}
                    if text:
                        d["text"] = text
                else:
                    parts = qr.split("<extra>", 1)
                    d = {"type": "text", "text": parts[0]}
                    if len(parts) > 1:
                        d["extra"] = parts[1]
                qrs.append(d)
            msg.quickreplies = qrs

        Msg.objects.bulk_update(batch, ["quickreplies"])

        num_updated += len(batch)
        print(f"Backfilled quickreplies on {num_updated} messages")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    backfill_msg_quickreplies(apps, None)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("msgs", "0304_msg_quickreplies"),
    ]

    operations = [
        migrations.RunPython(backfill_msg_quickreplies, reverse_code=migrations.RunPython.noop),
    ]
