# Generated by Django 5.2.10 on 2026-02-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0305_backfill_msg_quickreplies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="msg",
            name="quick_replies",
        ),
    ]
