# Generated by Django 6.0.7 on 2026-07-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0306_remove_msg_quick_replies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="media",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
