# Generated by Django 6.0.7 on 2026-08-11 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0214_remove_channelevent_optin"),
        ("flows", "0406_remove_flow_optin_dependencies"),
        ("msgs", "0307_alter_label_id_alter_media_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="optin",
            name="unique_optin_names",
        ),
        migrations.RemoveField(
            model_name="msg",
            name="optin",
        ),
        migrations.RemoveField(
            model_name="broadcast",
            name="optin",
        ),
        migrations.DeleteModel(
            name="OptIn",
        ),
    ]
