# Generated by Django 6.1 on 2026-08-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0308_remove_optin_unique_optin_names_remove_msg_optin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="msg",
            name="folder",
            field=models.CharField(
                choices=[
                    ("I", "Inbox"),
                    ("W", "Handled"),
                    ("A", "Archived"),
                    ("O", "Outbox"),
                    ("S", "Sent"),
                    ("X", "Failed"),
                    ("P", "Pending"),
                    ("D", "Deleted"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
