# Generated by Django 2.0.8 on 2018-08-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0174_populate_flow_is_system")]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="is_system",
            field=models.BooleanField(help_text="Whether this is a system created flow"),
        )
    ]
