# Generated by Django 2.2.4 on 2019-10-01 19:48

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [("sql", "0001_initial"), ("flows", "0218_auto_20190813_2014")]

    operations = [
        migrations.RunSQL("DROP INDEX flows_flowrun_timeout_active;"),
        migrations.RunSQL("DROP INDEX flows_flowrun_parent_created_on_not_null;"),
        migrations.RunSQL(
            """
            -- for finding runs to expire
            CREATE INDEX CONCURRENTLY flows_flowrun_expires_where_waiting ON flows_flowrun(expires_on) WHERE status = 'W';
            """
        ),
        migrations.RunSQL(
            """
            -- for finding a contact's runs to interrupt
            CREATE INDEX CONCURRENTLY flows_flowrun_contact_where_active_or_waiting ON flows_flowrun(contact_id) WHERE status IN ('A', 'W');
            """
        ),
    ]
