# Generated by Django 2.2.10 on 2021-01-20 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0074_auto_20201214_1714"),
        ("flows", "0246_auto_20210119_1717"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowStartTypeCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_squashed",
                    models.BooleanField(default=False, help_text="Whether this row was created by squashing"),
                ),
                (
                    "start_type",
                    models.CharField(
                        choices=[
                            ("M", "Manual"),
                            ("A", "API"),
                            ("Z", "Zapier"),
                            ("F", "Flow Action"),
                            ("T", "Trigger"),
                        ],
                        max_length=1,
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flow_starts_type_counts",
                        to="orgs.Org",
                    ),
                ),
            ],
            options={"index_together": {("org", "start_type")}},
        ),
    ]
