# Generated by Django 2.2.10 on 2021-03-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0247_auto_20210126_1834"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="flowrun",
            constraint=models.CheckConstraint(
                check=models.Q(("is_active", False), ("expires_on__isnull", False), _connector="OR"),
                name="flows_flowrun_active_runs_have_expirations",
            ),
        ),
    ]
