# Generated by Django 4.0.7 on 2022-10-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0192_broadcastcrudl"),
        ("flows", "0297_exportflowresultstask_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="broadcast_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="msgs.broadcast"),
        ),
    ]
