# Generated by Django 5.1.2 on 2024-11-20 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0337_alter_flowstart_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionTimer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("T", "Timeout"), ("E", "Expiration")], max_length=1)),
                ("time", models.DateTimeField()),
                (
                    "session",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timers",
                        to="flows.flowsession",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["time"], name="flows_sessi_time_c44534_idx")],
                "constraints": [models.UniqueConstraint(fields=("session", "type"), name="session_timer_unique")],
            },
        ),
    ]
