# Generated by Django 5.2.9 on 2026-01-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0397_alter_flowactivitycount_count_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="flowsession",
            name="flows_session_has_output_or_url",
        ),
        migrations.RemoveField(
            model_name="flowsession",
            name="output_url",
        ),
    ]
