# Generated by Django 5.2.10 on 2026-01-08 20:34

from django.db import migrations, models

import temba.utils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0398_remove_flowsession_flows_session_has_output_or_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowsession",
            name="contact_uuid",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="flowsession",
            name="output",
            field=temba.utils.models.fields.JSONAsTextField(default=dict),
        ),
    ]
