# Generated by Django 5.2.12 on 2026-03-31 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0216_remove_contact_contacts_contact_org_modified_and_more"),
        ("flows", "0399_alter_flowsession_contact_uuid_and_more"),
        ("orgs", "0179_orgmembership_can_assign_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="flowstart",
            index=models.Index(
                condition=models.Q(("status__in", ("P", "S"))),
                fields=["flow", "-created_on"],
                name="flows_flowstarts_flow_active",
            ),
        ),
    ]
