# Generated by Django 5.2.13 on 2026-04-29 18:13

from django.db import migrations

import temba.utils.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0400_flowstart_flows_flowstarts_flow_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowrevision",
            name="changes",
            field=temba.utils.models.fields.JSONAsTextField(default=None, null=True),
        ),
    ]
