# Generated by Django 5.2.13 on 2026-05-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0400_flowstart_flows_flowstarts_flow_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowrevision",
            name="changes",
            field=models.JSONField(default=None, null=True),
        ),
    ]
