# Generated by Django 6.0.7; hand-edited to keep contacts_contact FK columns as int so the
# large contacts_contact table is not rewritten. Postgres allows an int FK column to reference a
# bigint primary key, so contacts_contact's foreign keys are dropped and re-added (via the SQL
# below) without widening the columns. Constraint names are preserved so the operation is
# reversible. Django's model state still treats these columns as bigint (state_operations), so
# makemigrations stays clean.

from django.db import migrations, models

FORWARD_SQL = """
--
-- Alter field id on flow
--
SET CONSTRAINTS "flows_flow_channel_d_flow_id_764a1db2_fk_flows_flo" IMMEDIATE; ALTER TABLE "flows_flow_channel_dependencies" DROP CONSTRAINT "flows_flow_channel_d_flow_id_764a1db2_fk_flows_flo";
SET CONSTRAINTS "flows_flow_field_dependencies_flow_id_ee6ccf51_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flow_field_dependencies" DROP CONSTRAINT "flows_flow_field_dependencies_flow_id_ee6ccf51_fk_flows_flow_id";
SET CONSTRAINTS "flows_flow_flow_depe_from_flow_id_bee265be_fk_flows_flo" IMMEDIATE; ALTER TABLE "flows_flow_flow_dependencies" DROP CONSTRAINT "flows_flow_flow_depe_from_flow_id_bee265be_fk_flows_flo";
SET CONSTRAINTS "flows_flow_flow_depe_to_flow_id_015ac795_fk_flows_flo" IMMEDIATE; ALTER TABLE "flows_flow_flow_dependencies" DROP CONSTRAINT "flows_flow_flow_depe_to_flow_id_015ac795_fk_flows_flo";
SET CONSTRAINTS "flows_flow_global_de_flow_id_e4988650_fk_flows_flo" IMMEDIATE; ALTER TABLE "flows_flow_global_dependencies" DROP CONSTRAINT "flows_flow_global_de_flow_id_e4988650_fk_flows_flo";
SET CONSTRAINTS "flows_flow_group_dependencies_flow_id_de38b8ae_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flow_group_dependencies" DROP CONSTRAINT "flows_flow_group_dependencies_flow_id_de38b8ae_fk_flows_flow_id";
SET CONSTRAINTS "flows_flow_label_dependencies_flow_id_7e6aa4fb_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flow_label_dependencies" DROP CONSTRAINT "flows_flow_label_dependencies_flow_id_7e6aa4fb_fk_flows_flow_id";
SET CONSTRAINTS "flows_flow_labels_flow_id_b5b2fc3c_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flow_labels" DROP CONSTRAINT "flows_flow_labels_flow_id_b5b2fc3c_fk_flows_flow_id";
SET CONSTRAINTS "flows_flow_llm_dependencies_flow_id_ad900a9e_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flow_llm_dependencies" DROP CONSTRAINT "flows_flow_llm_dependencies_flow_id_ad900a9e_fk_flows_flow_id";
SET CONSTRAINTS "flows_flow_optin_dependencies_flow_id_6c117038_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flow_optin_dependencies" DROP CONSTRAINT "flows_flow_optin_dependencies_flow_id_6c117038_fk_flows_flow_id";
SET CONSTRAINTS "flows_flow_template__flow_id_57119aea_fk_flows_flo" IMMEDIATE; ALTER TABLE "flows_flow_template_dependencies" DROP CONSTRAINT "flows_flow_template__flow_id_57119aea_fk_flows_flo";
SET CONSTRAINTS "flows_flow_topic_dependencies_flow_id_016caef9_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flow_topic_dependencies" DROP CONSTRAINT "flows_flow_topic_dependencies_flow_id_016caef9_fk_flows_flow_id";
SET CONSTRAINTS "flows_flow_user_dependencies_flow_id_0e0ee262_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flow_user_dependencies" DROP CONSTRAINT "flows_flow_user_dependencies_flow_id_0e0ee262_fk_flows_flow_id";
SET CONSTRAINTS "contacts_contact_current_flow_id_4433e731_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "contacts_contact" DROP CONSTRAINT "contacts_contact_current_flow_id_4433e731_fk_flows_flow_id";
SET CONSTRAINTS "flows_flowactivitycount_flow_id_835a62dc_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flowactivitycount" DROP CONSTRAINT "flows_flowactivitycount_flow_id_835a62dc_fk_flows_flow_id";
SET CONSTRAINTS "flows_flowresultcount_flow_id_2a8a9ab9_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flowresultcount" DROP CONSTRAINT "flows_flowresultcount_flow_id_2a8a9ab9_fk_flows_flow_id";
SET CONSTRAINTS "flows_flowrevision_flow_id_4ae332c8_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flowrevision" DROP CONSTRAINT "flows_flowrevision_flow_id_4ae332c8_fk_flows_flow_id";
SET CONSTRAINTS "flows_flowrun_flow_id_9cbb3a32_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flowrun" DROP CONSTRAINT "flows_flowrun_flow_id_9cbb3a32_fk_flows_flow_id";
SET CONSTRAINTS "flows_flowstart_flow_id_c74e7d30_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flowstart" DROP CONSTRAINT "flows_flowstart_flow_id_c74e7d30_fk_flows_flow_id";
ALTER TABLE "flows_flow" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "flows_flow_id_seq" AS bigint;
ALTER TABLE "flows_flow_channel_dependencies" ALTER COLUMN "flow_id" TYPE bigint USING "flow_id"::bigint;
ALTER TABLE "flows_flow_field_dependencies" ALTER COLUMN "flow_id" TYPE bigint USING "flow_id"::bigint;
ALTER TABLE "flows_flow_flow_dependencies" ALTER COLUMN "from_flow_id" TYPE bigint USING "from_flow_id"::bigint;
ALTER TABLE "flows_flow_flow_dependencies" ALTER COLUMN "to_flow_id" TYPE bigint USING "to_flow_id"::bigint;
ALTER TABLE "flows_flow_global_dependencies" ALTER COLUMN "flow_id" TYPE bigint USING "flow_id"::bigint;
ALTER TABLE "flows_flow_group_dependencies" ALTER COLUMN "flow_id" TYPE bigint USING "flow_id"::bigint;
ALTER TABLE "flows_flow_label_dependencies" ALTER COLUMN "flow_id" TYPE bigint USING "flow_id"::bigint;
ALTER TABLE "flows_flow_labels" ALTER COLUMN "flow_id" TYPE bigint USING "flow_id"::bigint;
ALTER TABLE "flows_flow_llm_dependencies" ALTER COLUMN "flow_id" TYPE bigint USING "flow_id"::bigint;
ALTER TABLE "flows_flow_optin_dependencies" ALTER COLUMN "flow_id" TYPE bigint USING "flow_id"::bigint;
ALTER TABLE "flows_flow_template_dependencies" ALTER COLUMN "flow_id" TYPE bigint USING "flow_id"::bigint;
ALTER TABLE "flows_flow_topic_dependencies" ALTER COLUMN "flow_id" TYPE bigint USING "flow_id"::bigint;
ALTER TABLE "flows_flow_user_dependencies" ALTER COLUMN "flow_id" TYPE bigint USING "flow_id"::bigint;
ALTER TABLE "flows_flowactivitycount" ALTER COLUMN "flow_id" TYPE bigint USING "flow_id"::bigint;
ALTER TABLE "flows_flowresultcount" ALTER COLUMN "flow_id" TYPE bigint USING "flow_id"::bigint;
ALTER TABLE "flows_flowrevision" ALTER COLUMN "flow_id" TYPE bigint USING "flow_id"::bigint;
ALTER TABLE "flows_flowrun" ALTER COLUMN "flow_id" TYPE bigint USING "flow_id"::bigint;
ALTER TABLE "flows_flowstart" ALTER COLUMN "flow_id" TYPE bigint USING "flow_id"::bigint;
ALTER TABLE "flows_flow_channel_dependencies" ADD CONSTRAINT "flows_flow_channel_d_flow_id_764a1db2_fk_flows_flo" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_field_dependencies" ADD CONSTRAINT "flows_flow_field_dependencies_flow_id_ee6ccf51_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_flow_dependencies" ADD CONSTRAINT "flows_flow_flow_depe_from_flow_id_bee265be_fk_flows_flo" FOREIGN KEY ("from_flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_flow_dependencies" ADD CONSTRAINT "flows_flow_flow_depe_to_flow_id_015ac795_fk_flows_flo" FOREIGN KEY ("to_flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_global_dependencies" ADD CONSTRAINT "flows_flow_global_de_flow_id_e4988650_fk_flows_flo" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_group_dependencies" ADD CONSTRAINT "flows_flow_group_dependencies_flow_id_de38b8ae_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_label_dependencies" ADD CONSTRAINT "flows_flow_label_dependencies_flow_id_7e6aa4fb_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_labels" ADD CONSTRAINT "flows_flow_labels_flow_id_b5b2fc3c_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_llm_dependencies" ADD CONSTRAINT "flows_flow_llm_dependencies_flow_id_ad900a9e_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_optin_dependencies" ADD CONSTRAINT "flows_flow_optin_dependencies_flow_id_6c117038_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_template_dependencies" ADD CONSTRAINT "flows_flow_template__flow_id_57119aea_fk_flows_flo" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_topic_dependencies" ADD CONSTRAINT "flows_flow_topic_dependencies_flow_id_016caef9_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_user_dependencies" ADD CONSTRAINT "flows_flow_user_dependencies_flow_id_0e0ee262_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contact" ADD CONSTRAINT "contacts_contact_current_flow_id_4433e731_fk_flows_flow_id" FOREIGN KEY ("current_flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowactivitycount" ADD CONSTRAINT "flows_flowactivitycount_flow_id_835a62dc_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowresultcount" ADD CONSTRAINT "flows_flowresultcount_flow_id_2a8a9ab9_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowrevision" ADD CONSTRAINT "flows_flowrevision_flow_id_4ae332c8_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowrun" ADD CONSTRAINT "flows_flowrun_flow_id_9cbb3a32_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowstart" ADD CONSTRAINT "flows_flowstart_flow_id_c74e7d30_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
--
-- Alter field id on flowlabel
--
SET CONSTRAINTS "flows_flow_labels_flowlabel_id_ce11c90a_fk_flows_flowlabel_id" IMMEDIATE; ALTER TABLE "flows_flow_labels" DROP CONSTRAINT "flows_flow_labels_flowlabel_id_ce11c90a_fk_flows_flowlabel_id";
ALTER TABLE "flows_flowlabel" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "flows_flowlabel_id_seq" AS bigint;
ALTER TABLE "flows_flow_labels" ALTER COLUMN "flowlabel_id" TYPE bigint USING "flowlabel_id"::bigint;
ALTER TABLE "flows_flow_labels" ADD CONSTRAINT "flows_flow_labels_flowlabel_id_ce11c90a_fk_flows_flowlabel_id" FOREIGN KEY ("flowlabel_id") REFERENCES "flows_flowlabel" ("id") DEFERRABLE INITIALLY DEFERRED;
--
-- Alter field id on flowrevision
--
ALTER TABLE "flows_flowrevision" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "flows_flowrevision_id_seq" AS bigint;
--
-- Alter field id on flowstart
--
SET CONSTRAINTS "flows_flowstart_cont_flowstart_id_d8b4cf8f_fk_flows_flo" IMMEDIATE; ALTER TABLE "flows_flowstart_contacts" DROP CONSTRAINT "flows_flowstart_cont_flowstart_id_d8b4cf8f_fk_flows_flo";
SET CONSTRAINTS "flows_flowstart_grou_flowstart_id_b44aad1f_fk_flows_flo" IMMEDIATE; ALTER TABLE "flows_flowstart_groups" DROP CONSTRAINT "flows_flowstart_grou_flowstart_id_b44aad1f_fk_flows_flo";
SET CONSTRAINTS "flows_flowstartcount_start_id_a149293f_fk_flows_flowstart_id" IMMEDIATE; ALTER TABLE "flows_flowstartcount" DROP CONSTRAINT "flows_flowstartcount_start_id_a149293f_fk_flows_flowstart_id";
SET CONSTRAINTS "flows_flowrun_start_id_6f5f00b9_fk_flows_flowstart_id" IMMEDIATE; ALTER TABLE "flows_flowrun" DROP CONSTRAINT "flows_flowrun_start_id_6f5f00b9_fk_flows_flowstart_id";
ALTER TABLE "flows_flowstart" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "flows_flowstart_id_seq" AS bigint;
ALTER TABLE "flows_flowstart_contacts" ALTER COLUMN "flowstart_id" TYPE bigint USING "flowstart_id"::bigint;
ALTER TABLE "flows_flowstart_groups" ALTER COLUMN "flowstart_id" TYPE bigint USING "flowstart_id"::bigint;
ALTER TABLE "flows_flowstartcount" ALTER COLUMN "start_id" TYPE bigint USING "start_id"::bigint;
ALTER TABLE "flows_flowrun" ALTER COLUMN "start_id" TYPE bigint USING "start_id"::bigint;
ALTER TABLE "flows_flowstart_contacts" ADD CONSTRAINT "flows_flowstart_cont_flowstart_id_d8b4cf8f_fk_flows_flo" FOREIGN KEY ("flowstart_id") REFERENCES "flows_flowstart" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowstart_groups" ADD CONSTRAINT "flows_flowstart_grou_flowstart_id_b44aad1f_fk_flows_flo" FOREIGN KEY ("flowstart_id") REFERENCES "flows_flowstart" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowstartcount" ADD CONSTRAINT "flows_flowstartcount_start_id_a149293f_fk_flows_flowstart_id" FOREIGN KEY ("start_id") REFERENCES "flows_flowstart" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowrun" ADD CONSTRAINT "flows_flowrun_start_id_6f5f00b9_fk_flows_flowstart_id" FOREIGN KEY ("start_id") REFERENCES "flows_flowstart" ("id") DEFERRABLE INITIALLY DEFERRED;
"""

REVERSE_SQL = """
--
-- Alter field id on flowstart
--
SET CONSTRAINTS "flows_flowstart_cont_flowstart_id_d8b4cf8f_fk_flows_flo" IMMEDIATE; ALTER TABLE "flows_flowstart_contacts" DROP CONSTRAINT "flows_flowstart_cont_flowstart_id_d8b4cf8f_fk_flows_flo";
SET CONSTRAINTS "flows_flowstart_grou_flowstart_id_b44aad1f_fk_flows_flo" IMMEDIATE; ALTER TABLE "flows_flowstart_groups" DROP CONSTRAINT "flows_flowstart_grou_flowstart_id_b44aad1f_fk_flows_flo";
SET CONSTRAINTS "flows_flowstartcount_start_id_a149293f_fk_flows_flowstart_id" IMMEDIATE; ALTER TABLE "flows_flowstartcount" DROP CONSTRAINT "flows_flowstartcount_start_id_a149293f_fk_flows_flowstart_id";
SET CONSTRAINTS "flows_flowrun_start_id_6f5f00b9_fk_flows_flowstart_id" IMMEDIATE; ALTER TABLE "flows_flowrun" DROP CONSTRAINT "flows_flowrun_start_id_6f5f00b9_fk_flows_flowstart_id";
ALTER TABLE "flows_flowstart" ALTER COLUMN "id" TYPE integer USING "id"::integer;
ALTER SEQUENCE IF EXISTS "flows_flowstart_id_seq" AS integer;
ALTER TABLE "flows_flowstart_contacts" ALTER COLUMN "flowstart_id" TYPE integer USING "flowstart_id"::integer;
ALTER TABLE "flows_flowstart_groups" ALTER COLUMN "flowstart_id" TYPE integer USING "flowstart_id"::integer;
ALTER TABLE "flows_flowstartcount" ALTER COLUMN "start_id" TYPE integer USING "start_id"::integer;
ALTER TABLE "flows_flowrun" ALTER COLUMN "start_id" TYPE integer USING "start_id"::integer;
ALTER TABLE "flows_flowstart_contacts" ADD CONSTRAINT "flows_flowstart_cont_flowstart_id_d8b4cf8f_fk_flows_flo" FOREIGN KEY ("flowstart_id") REFERENCES "flows_flowstart" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowstart_groups" ADD CONSTRAINT "flows_flowstart_grou_flowstart_id_b44aad1f_fk_flows_flo" FOREIGN KEY ("flowstart_id") REFERENCES "flows_flowstart" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowstartcount" ADD CONSTRAINT "flows_flowstartcount_start_id_a149293f_fk_flows_flowstart_id" FOREIGN KEY ("start_id") REFERENCES "flows_flowstart" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowrun" ADD CONSTRAINT "flows_flowrun_start_id_6f5f00b9_fk_flows_flowstart_id" FOREIGN KEY ("start_id") REFERENCES "flows_flowstart" ("id") DEFERRABLE INITIALLY DEFERRED;
--
-- Alter field id on flowrevision
--
ALTER TABLE "flows_flowrevision" ALTER COLUMN "id" TYPE integer USING "id"::integer;
ALTER SEQUENCE IF EXISTS "flows_flowrevision_id_seq" AS integer;
--
-- Alter field id on flowlabel
--
SET CONSTRAINTS "flows_flow_labels_flowlabel_id_ce11c90a_fk_flows_flowlabel_id" IMMEDIATE; ALTER TABLE "flows_flow_labels" DROP CONSTRAINT "flows_flow_labels_flowlabel_id_ce11c90a_fk_flows_flowlabel_id";
ALTER TABLE "flows_flowlabel" ALTER COLUMN "id" TYPE integer USING "id"::integer;
ALTER SEQUENCE IF EXISTS "flows_flowlabel_id_seq" AS integer;
ALTER TABLE "flows_flow_labels" ALTER COLUMN "flowlabel_id" TYPE integer USING "flowlabel_id"::integer;
ALTER TABLE "flows_flow_labels" ADD CONSTRAINT "flows_flow_labels_flowlabel_id_ce11c90a_fk_flows_flowlabel_id" FOREIGN KEY ("flowlabel_id") REFERENCES "flows_flowlabel" ("id") DEFERRABLE INITIALLY DEFERRED;
--
-- Alter field id on flow
--
SET CONSTRAINTS "flows_flow_channel_d_flow_id_764a1db2_fk_flows_flo" IMMEDIATE; ALTER TABLE "flows_flow_channel_dependencies" DROP CONSTRAINT "flows_flow_channel_d_flow_id_764a1db2_fk_flows_flo";
SET CONSTRAINTS "flows_flow_field_dependencies_flow_id_ee6ccf51_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flow_field_dependencies" DROP CONSTRAINT "flows_flow_field_dependencies_flow_id_ee6ccf51_fk_flows_flow_id";
SET CONSTRAINTS "flows_flow_flow_depe_from_flow_id_bee265be_fk_flows_flo" IMMEDIATE; ALTER TABLE "flows_flow_flow_dependencies" DROP CONSTRAINT "flows_flow_flow_depe_from_flow_id_bee265be_fk_flows_flo";
SET CONSTRAINTS "flows_flow_flow_depe_to_flow_id_015ac795_fk_flows_flo" IMMEDIATE; ALTER TABLE "flows_flow_flow_dependencies" DROP CONSTRAINT "flows_flow_flow_depe_to_flow_id_015ac795_fk_flows_flo";
SET CONSTRAINTS "flows_flow_global_de_flow_id_e4988650_fk_flows_flo" IMMEDIATE; ALTER TABLE "flows_flow_global_dependencies" DROP CONSTRAINT "flows_flow_global_de_flow_id_e4988650_fk_flows_flo";
SET CONSTRAINTS "flows_flow_group_dependencies_flow_id_de38b8ae_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flow_group_dependencies" DROP CONSTRAINT "flows_flow_group_dependencies_flow_id_de38b8ae_fk_flows_flow_id";
SET CONSTRAINTS "flows_flow_label_dependencies_flow_id_7e6aa4fb_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flow_label_dependencies" DROP CONSTRAINT "flows_flow_label_dependencies_flow_id_7e6aa4fb_fk_flows_flow_id";
SET CONSTRAINTS "flows_flow_labels_flow_id_b5b2fc3c_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flow_labels" DROP CONSTRAINT "flows_flow_labels_flow_id_b5b2fc3c_fk_flows_flow_id";
SET CONSTRAINTS "flows_flow_llm_dependencies_flow_id_ad900a9e_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flow_llm_dependencies" DROP CONSTRAINT "flows_flow_llm_dependencies_flow_id_ad900a9e_fk_flows_flow_id";
SET CONSTRAINTS "flows_flow_optin_dependencies_flow_id_6c117038_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flow_optin_dependencies" DROP CONSTRAINT "flows_flow_optin_dependencies_flow_id_6c117038_fk_flows_flow_id";
SET CONSTRAINTS "flows_flow_template__flow_id_57119aea_fk_flows_flo" IMMEDIATE; ALTER TABLE "flows_flow_template_dependencies" DROP CONSTRAINT "flows_flow_template__flow_id_57119aea_fk_flows_flo";
SET CONSTRAINTS "flows_flow_topic_dependencies_flow_id_016caef9_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flow_topic_dependencies" DROP CONSTRAINT "flows_flow_topic_dependencies_flow_id_016caef9_fk_flows_flow_id";
SET CONSTRAINTS "flows_flow_user_dependencies_flow_id_0e0ee262_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flow_user_dependencies" DROP CONSTRAINT "flows_flow_user_dependencies_flow_id_0e0ee262_fk_flows_flow_id";
SET CONSTRAINTS "contacts_contact_current_flow_id_4433e731_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "contacts_contact" DROP CONSTRAINT "contacts_contact_current_flow_id_4433e731_fk_flows_flow_id";
SET CONSTRAINTS "flows_flowactivitycount_flow_id_835a62dc_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flowactivitycount" DROP CONSTRAINT "flows_flowactivitycount_flow_id_835a62dc_fk_flows_flow_id";
SET CONSTRAINTS "flows_flowresultcount_flow_id_2a8a9ab9_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flowresultcount" DROP CONSTRAINT "flows_flowresultcount_flow_id_2a8a9ab9_fk_flows_flow_id";
SET CONSTRAINTS "flows_flowrevision_flow_id_4ae332c8_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flowrevision" DROP CONSTRAINT "flows_flowrevision_flow_id_4ae332c8_fk_flows_flow_id";
SET CONSTRAINTS "flows_flowrun_flow_id_9cbb3a32_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flowrun" DROP CONSTRAINT "flows_flowrun_flow_id_9cbb3a32_fk_flows_flow_id";
SET CONSTRAINTS "flows_flowstart_flow_id_c74e7d30_fk_flows_flow_id" IMMEDIATE; ALTER TABLE "flows_flowstart" DROP CONSTRAINT "flows_flowstart_flow_id_c74e7d30_fk_flows_flow_id";
ALTER TABLE "flows_flow" ALTER COLUMN "id" TYPE integer USING "id"::integer;
ALTER SEQUENCE IF EXISTS "flows_flow_id_seq" AS integer;
ALTER TABLE "flows_flow_channel_dependencies" ALTER COLUMN "flow_id" TYPE integer USING "flow_id"::integer;
ALTER TABLE "flows_flow_field_dependencies" ALTER COLUMN "flow_id" TYPE integer USING "flow_id"::integer;
ALTER TABLE "flows_flow_flow_dependencies" ALTER COLUMN "from_flow_id" TYPE integer USING "from_flow_id"::integer;
ALTER TABLE "flows_flow_flow_dependencies" ALTER COLUMN "to_flow_id" TYPE integer USING "to_flow_id"::integer;
ALTER TABLE "flows_flow_global_dependencies" ALTER COLUMN "flow_id" TYPE integer USING "flow_id"::integer;
ALTER TABLE "flows_flow_group_dependencies" ALTER COLUMN "flow_id" TYPE integer USING "flow_id"::integer;
ALTER TABLE "flows_flow_label_dependencies" ALTER COLUMN "flow_id" TYPE integer USING "flow_id"::integer;
ALTER TABLE "flows_flow_labels" ALTER COLUMN "flow_id" TYPE integer USING "flow_id"::integer;
ALTER TABLE "flows_flow_llm_dependencies" ALTER COLUMN "flow_id" TYPE integer USING "flow_id"::integer;
ALTER TABLE "flows_flow_optin_dependencies" ALTER COLUMN "flow_id" TYPE integer USING "flow_id"::integer;
ALTER TABLE "flows_flow_template_dependencies" ALTER COLUMN "flow_id" TYPE integer USING "flow_id"::integer;
ALTER TABLE "flows_flow_topic_dependencies" ALTER COLUMN "flow_id" TYPE integer USING "flow_id"::integer;
ALTER TABLE "flows_flow_user_dependencies" ALTER COLUMN "flow_id" TYPE integer USING "flow_id"::integer;
ALTER TABLE "flows_flowactivitycount" ALTER COLUMN "flow_id" TYPE integer USING "flow_id"::integer;
ALTER TABLE "flows_flowresultcount" ALTER COLUMN "flow_id" TYPE integer USING "flow_id"::integer;
ALTER TABLE "flows_flowrevision" ALTER COLUMN "flow_id" TYPE integer USING "flow_id"::integer;
ALTER TABLE "flows_flowrun" ALTER COLUMN "flow_id" TYPE integer USING "flow_id"::integer;
ALTER TABLE "flows_flowstart" ALTER COLUMN "flow_id" TYPE integer USING "flow_id"::integer;
ALTER TABLE "flows_flow_channel_dependencies" ADD CONSTRAINT "flows_flow_channel_d_flow_id_764a1db2_fk_flows_flo" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_field_dependencies" ADD CONSTRAINT "flows_flow_field_dependencies_flow_id_ee6ccf51_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_flow_dependencies" ADD CONSTRAINT "flows_flow_flow_depe_from_flow_id_bee265be_fk_flows_flo" FOREIGN KEY ("from_flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_flow_dependencies" ADD CONSTRAINT "flows_flow_flow_depe_to_flow_id_015ac795_fk_flows_flo" FOREIGN KEY ("to_flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_global_dependencies" ADD CONSTRAINT "flows_flow_global_de_flow_id_e4988650_fk_flows_flo" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_group_dependencies" ADD CONSTRAINT "flows_flow_group_dependencies_flow_id_de38b8ae_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_label_dependencies" ADD CONSTRAINT "flows_flow_label_dependencies_flow_id_7e6aa4fb_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_labels" ADD CONSTRAINT "flows_flow_labels_flow_id_b5b2fc3c_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_llm_dependencies" ADD CONSTRAINT "flows_flow_llm_dependencies_flow_id_ad900a9e_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_optin_dependencies" ADD CONSTRAINT "flows_flow_optin_dependencies_flow_id_6c117038_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_template_dependencies" ADD CONSTRAINT "flows_flow_template__flow_id_57119aea_fk_flows_flo" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_topic_dependencies" ADD CONSTRAINT "flows_flow_topic_dependencies_flow_id_016caef9_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flow_user_dependencies" ADD CONSTRAINT "flows_flow_user_dependencies_flow_id_0e0ee262_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contacts_contact" ADD CONSTRAINT "contacts_contact_current_flow_id_4433e731_fk_flows_flow_id" FOREIGN KEY ("current_flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowactivitycount" ADD CONSTRAINT "flows_flowactivitycount_flow_id_835a62dc_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowresultcount" ADD CONSTRAINT "flows_flowresultcount_flow_id_2a8a9ab9_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowrevision" ADD CONSTRAINT "flows_flowrevision_flow_id_4ae332c8_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowrun" ADD CONSTRAINT "flows_flowrun_flow_id_9cbb3a32_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "flows_flowstart" ADD CONSTRAINT "flows_flowstart_flow_id_c74e7d30_fk_flows_flow_id" FOREIGN KEY ("flow_id") REFERENCES "flows_flow" ("id") DEFERRABLE INITIALLY DEFERRED;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0403_remove_flow_classifier_dependencies"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="flow",
                    name="id",
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                migrations.AlterField(
                    model_name="flowlabel",
                    name="id",
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                migrations.AlterField(
                    model_name="flowrevision",
                    name="id",
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                migrations.AlterField(
                    model_name="flowstart",
                    name="id",
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
            ],
            database_operations=[migrations.RunSQL(FORWARD_SQL, reverse_sql=REVERSE_SQL)],
        ),
    ]
