# Generated by Django 6.0.7 on 2026-07-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0404_alter_flowlabel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowrevision",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
