# Generated by Django 6.0.7 on 2026-08-11 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0405_alter_flow_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flow",
            name="optin_dependencies",
        ),
    ]
