# Generated by Django 5.2.2 on 2026-08-18 00:00

from django.db import migrations

SQL = """
----------------------------------------------------------------------
-- Handles DELETE statements on flowrun table
----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION temba_flowrun_on_delete() RETURNS TRIGGER AS $$
BEGIN
    -- add negative status counts for any deleted runs which were still active or waiting
    INSERT INTO flows_flowactivitycount("flow_id", "scope", "count", "is_squashed")
    SELECT flow_id, format('status:%s', status), -count(*), FALSE FROM oldtab
    WHERE status IN ('A', 'W') GROUP BY 1, 2;

    -- add negative node counts for any deleted runs sitting at a node
    INSERT INTO flows_flowactivitycount("flow_id", "scope", "count", "is_squashed")
    SELECT flow_id, format('node:%s', current_node_uuid), -count(*), FALSE FROM oldtab
    WHERE status IN ('A', 'W') AND current_node_uuid IS NOT NULL GROUP BY 1, 2;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER temba_flowrun_on_delete
AFTER DELETE ON flows_flowrun REFERENCING OLD TABLE AS oldtab
FOR EACH STATEMENT EXECUTE PROCEDURE temba_flowrun_on_delete();
"""

REVERSE_SQL = """
DROP TRIGGER temba_flowrun_on_delete ON flows_flowrun;
DROP FUNCTION temba_flowrun_on_delete();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0406_remove_flow_optin_dependencies"),
        ("sql", "0008_squashed"),
    ]

    operations = [
        migrations.RunSQL(SQL, REVERSE_SQL),
    ]
