# Generated by Django 5.2.2 on 2026-08-18 00:00

from django.db import migrations

# runs could previously be deleted (e.g. by contact deletion) whilst still active or waiting, without their status and
# node counts being decremented. Each statement compares counts to actual runs and inserts corrective count rows, and
# being a single statement, is consistent even with runs being updated concurrently.

SQL_FIX_STATUS_COUNTS = """
WITH counted AS (
    SELECT flow_id, scope, sum(count) AS total
    FROM flows_flowactivitycount
    WHERE scope IN ('status:A', 'status:W')
    GROUP BY flow_id, scope
),
actual AS (
    SELECT flow_id, format('status:%s', status) AS scope, count(*) AS total
    FROM flows_flowrun
    WHERE status IN ('A', 'W')
    GROUP BY flow_id, status
)
INSERT INTO flows_flowactivitycount(flow_id, scope, count, is_squashed)
SELECT COALESCE(c.flow_id, a.flow_id), COALESCE(c.scope, a.scope), COALESCE(a.total, 0) - COALESCE(c.total, 0), FALSE
FROM counted c
FULL JOIN actual a ON a.flow_id = c.flow_id AND a.scope = c.scope
WHERE COALESCE(c.total, 0) != COALESCE(a.total, 0)
"""

SQL_FIX_NODE_COUNTS = """
WITH counted AS (
    SELECT flow_id, scope, sum(count) AS total
    FROM flows_flowactivitycount
    WHERE scope LIKE 'node:%'
    GROUP BY flow_id, scope
),
actual AS (
    SELECT flow_id, format('node:%s', current_node_uuid) AS scope, count(*) AS total
    FROM flows_flowrun
    WHERE status IN ('A', 'W') AND current_node_uuid IS NOT NULL
    GROUP BY flow_id, current_node_uuid
)
INSERT INTO flows_flowactivitycount(flow_id, scope, count, is_squashed)
SELECT COALESCE(c.flow_id, a.flow_id), COALESCE(c.scope, a.scope), COALESCE(a.total, 0) - COALESCE(c.total, 0), FALSE
FROM counted c
FULL JOIN actual a ON a.flow_id = c.flow_id AND a.scope = c.scope
WHERE COALESCE(c.total, 0) != COALESCE(a.total, 0)
"""


def fix_activity_counts(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(SQL_FIX_STATUS_COUNTS)
        if cursor.rowcount:
            print(f"Fixed status counts for flows with {cursor.rowcount} corrective count rows")

        cursor.execute(SQL_FIX_NODE_COUNTS)
        if cursor.rowcount:
            print(f"Fixed node counts for flows with {cursor.rowcount} corrective count rows")


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0407_update_triggers"),
    ]

    operations = [
        migrations.RunPython(fix_activity_counts, migrations.RunPython.noop),
    ]
