# Generated by Django 5.1.4 on 2025-01-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0034_populate_locations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boundaryalias",
            name="boundary",
        ),
        migrations.RemoveField(
            model_name="boundaryalias",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="boundaryalias",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="boundaryalias",
            name="org",
        ),
        migrations.DeleteModel(
            name="AdminBoundary",
        ),
        migrations.DeleteModel(
            name="BoundaryAlias",
        ),
    ]
