# Generated by Django 6.0.7 on 2026-07-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0037_squashed"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="adminboundary",
            index=models.Index(fields=["tree_id", "lft"], name="locations_adminboundary_tr0dec"),
        ),
    ]
