# Generated by Django 4.0.4 on 2022-05-05 22:03

from django.db import migrations, models

import temba.utils.fields
import temba.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ("globals", "0007_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="global",
            name="key",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="global",
            name="name",
            field=models.CharField(max_length=64, validators=[temba.utils.fields.NameValidator(64)]),
        ),
        migrations.AlterField(
            model_name="global",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, unique=True),
        ),
    ]
