# Generated by Django 6.0.7 on 2026-07-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globals", "0016_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="global",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
