# Generated by Django 5.2.12 on 2026-04-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0007_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="llm",
            name="roles",
            field=models.CharField(default="TF", max_length=2),
        ),
    ]
