# Generated by Django 5.2.13 on 2026-04-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0008_llm_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="llm",
            name="max_output_tokens",
            field=models.PositiveIntegerField(default=4096),
        ),
    ]
