# Generated by Django 5.2.13 on 2026-05-18 10:31
from django.db import migrations


def update_deepseek_model(apps, schema_editor):  # pragma: no cover
    LLM = apps.get_model("ai", "LLM")
    LLM.objects.filter(llm_type="deepseek", model="deepseek-chat").update(model="deepseek-v4-flash")


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0011_llmcount"),
    ]

    operations = [
        migrations.RunPython(update_deepseek_model, migrations.RunPython.noop),
    ]
