# Generated by Django 5.2.14 on 2026-06-11 17:40

import pgvector.django.indexes
import pgvector.django.vector

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import temba.ai.models
import temba.utils.fields
import temba.utils.uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0013_vector_extension"),
        ("orgs", "0182_remove_org_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2048, null=True)),
                (
                    "file",
                    models.FileField(
                        max_length=2048,
                        null=True,
                        upload_to=temba.ai.models.get_document_path,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item is active, use this instead of deleting",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                ("uuid", models.UUIDField(default=temba.utils.uuid.uuid4, unique=True)),
                (
                    "name",
                    models.CharField(max_length=64, validators=[temba.utils.fields.NameValidator(64)]),
                ),
                ("is_system", models.BooleanField(default=False)),
                (
                    "kb_type",
                    models.CharField(
                        choices=[("W", "Website"), ("D", "Documents"), ("F", "FAQ")],
                        default="W",
                        max_length=1,
                    ),
                ),
                ("url", models.URLField(max_length=2048, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("O", "Processing"),
                            ("C", "Complete"),
                            ("F", "Failed"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("error", models.CharField(max_length=255, null=True)),
                ("crawl_state", models.JSONField(default=dict)),
                ("num_pages", models.IntegerField(default=0)),
                ("num_articles", models.IntegerField(default=0)),
                ("num_chunks", models.IntegerField(default=0)),
                ("content_chars", models.IntegerField(default=0)),
                ("started_on", models.DateTimeField(null=True)),
                ("finished_on", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_bases",
                        to="orgs.org",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticleChunk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chunks",
                        to="ai.article",
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chunks",
                        to="ai.knowledgebase",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="knowledge_base",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="ai.knowledgebase",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgebase",
            constraint=models.UniqueConstraint(
                models.F("org"),
                django.db.models.functions.text.Lower("name"),
                name="unique_knowledgebase_names",
            ),
        ),
        migrations.AddIndex(
            model_name="articlechunk",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="articlechunk_embedding",
                opclasses=("vector_cosine_ops",),
            ),
        ),
    ]
