# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 19:32
from __future__ import unicode_literals

from django.db import migrations


def remove_id_for_anon(apps, schema_editor):
    ContactField = apps.get_model('contacts', 'ContactField')
    fields = ContactField.objects.filter(key='id', is_active=True, org__is_anon=True)
    for field in fields:
        field.dependent_flows.clear()
        field.release()


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0067_auto_20170808_1852'),
    ]

    operations = [
        migrations.RunPython(remove_id_for_anon)
    ]
