# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 11:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0069_iso639-3'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='_fields_as_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
