# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 11:00
from __future__ import unicode_literals

from django.db import migrations
import temba.contacts.models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0069_iso639-3'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='fields_as_json',
            field=temba.contacts.models.JSONAsText(default={}),
        ),
    ]
