# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 20:04
from __future__ import unicode_literals

from django.db import migrations, connection


def create_pgtrgm_gin_index():
    with connection.cursor() as c:
        c.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm";')

        c.execute('DROP INDEX IF EXISTS public.contacts_contacturn_path CASCADE;')

        c.execute(
            'CREATE INDEX CONCURRENTLY contacturn_trigram_path ON contacts_contacturn '
            'USING gin (UPPER(path) gin_trgm_ops);'
        )

        c.execute('VACUUM ANALYSE contacts_contacturn;')


def apply_manual():
    create_pgtrgm_gin_index()


def apply_as_migration(apps, schema_editor):
    create_pgtrgm_gin_index()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('contacts', '0069_iso639-3'),
    ]

    operations = [
        migrations.RunPython(apply_as_migration)
    ]
