# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-06 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("contacts", "0080_contactfield_priority")]

    operations = [
        migrations.AddField(
            model_name="exportcontactstask",
            name="group_membership",
            field=models.BooleanField(default=False, help_text="Whether this export should include group membership"),
        )
    ]
