# Generated by Django 2.2.4 on 2020-04-21 19:10

from django.db import migrations

BATCH_SIZE = 5000


def populate_contact_is_paused(apps, schema_editor):  # pragma: no cover
    Contact = apps.get_model("contacts", "Contact")

    contact_ids = Contact.objects.filter(is_paused=None).values_list("id", flat=True)

    num_updated = 0
    max_id = -1
    while True:
        batch_ids = list(contact_ids.filter(id__gt=max_id).order_by("id")[:BATCH_SIZE])
        if not batch_ids:
            break

        Contact.objects.filter(id__in=batch_ids).update(is_paused=False)

        num_updated += len(batch_ids)
        print(f" > Updated {num_updated} contacts with is_paused")

        max_id = batch_ids[-1]


def reverse(apps, schema_editor):  # pragma: no cover
    pass


def apply_manual():  # pragma: no cover
    from django.apps import apps

    populate_contact_is_paused(apps, None)


class Migration(migrations.Migration):

    dependencies = [("contacts", "0106_contact_is_paused")]

    operations = [migrations.RunPython(populate_contact_is_paused)]
