# Generated by Django 2.2.4 on 2020-04-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("contacts", "0106_contact_is_paused")]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="pause_type",
            field=models.CharField(
                choices=[("B", "Blocked"), ("S", "Stopped"), ("T", "Ticket")], max_length=1, null=True
            ),
        ),
        migrations.AddField(model_name="contact", name="paused_on", field=models.DateTimeField(null=True)),
        migrations.AlterField(model_name="contact", name="is_paused", field=models.BooleanField(null=True)),
    ]
