# Generated by Django 2.2.20 on 2021-06-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0135_auto_20210712_1845"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactgroup",
            name="query_fields",
            field=models.ManyToManyField(related_name="dependent_groups", to="contacts.ContactField"),
        ),
    ]
