# Generated by Django 3.2.7 on 2021-09-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0143_auto_20210908_2224"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactgroup",
            name="is_system",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="contactgroup",
            name="group_type",
            field=models.CharField(
                choices=[("A", "Active"), ("B", "Blocked"), ("S", "Stopped"), ("V", "Archived"), ("U", "Non-status")],
                default="U",
                max_length=1,
            ),
        ),
    ]
