# Generated by Django 5.2.12 on 2026-03-30 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0215_fix_bad_last_seen_ons"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contact",
            name="contacts_contact_org_modified",
        ),
        migrations.RemoveIndex(
            model_name="contact",
            name="contacts_modified",
        ),
    ]
