# Generated by Django 6.0.7 on 2026-07-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0216_remove_contact_contacts_contact_org_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactfield",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="contactimport",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="contactimportbatch",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="contactnote",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
