# Generated by Django 6.0.7 on 2026-07-31 16:31

from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0217_alter_contactfield_id_alter_contactimport_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactgroup",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, unique=True),
        ),
    ]
