# Generated by Django 2.2.10 on 2020-09-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_logs", "0007_auto_20200526_1931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("intents_synced", "Intents Synced"),
                    ("classifier_called", "Classifier Called"),
                    ("ticketer_called", "Ticketing Service Called"),
                    ("ticketer_incoming", "Ticketing Service Incoming"),
                    ("airtime_transferred", "Airtime Transferred"),
                    ("whatsapp_templates_synced", "WhatsApp Templates Synced"),
                    ("whatsapp_tokens_synced", "WhatsApp Tokens Synced"),
                    ("whatsapp_contacts_refreshed", "WhatsApp Contacts Refreshed"),
                ],
                max_length=32,
            ),
        ),
    ]
