# Generated by Django 2.2.10 on 2020-12-09 18:46

from uuid import uuid4

from django.db import migrations

INTERNAL_SLUG = "internal"
INTERNAL_NAME = "Internal"


def add_internal_ticketers(apps, schema_editor):
    Org = apps.get_model("orgs", "Org")
    for org in Org.objects.filter():
        if not org.ticketers.filter(ticketer_type=INTERNAL_SLUG).exists():
            org.ticketers.create(
                uuid=uuid4(),
                ticketer_type=INTERNAL_SLUG,
                name=INTERNAL_NAME,
                config={},
                created_by=org.created_by,
                modified_by=org.created_by,
            )


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_squashed"),
    ]

    operations = [
        migrations.RunPython(add_internal_ticketers, reverse),
    ]
