# Generated by Django 6.0.7 on 2026-07-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0088_alter_shortcut_id_alter_team_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
