# Generated by Django 6.0.7 on 2026-07-28 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0217_alter_contactfield_id_alter_contactimport_id_and_more"),
        ("flows", "0404_alter_flowlabel_id"),
        ("orgs", "0186_alter_export_id_alter_invitation_id_and_more"),
        ("tickets", "0088_alter_shortcut_id_alter_team_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ticket",
            name="tickets_org_status",
        ),
        migrations.RemoveIndex(
            model_name="ticket",
            name="tickets_org_assignee_status",
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["org", "-status", "-last_activity_on", "-id"], name="tickets_org_status"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["org", "assignee", "-status", "-last_activity_on", "-id"], name="tickets_org_assignee_status"
            ),
        ),
    ]
