# Generated by Django 6.0.7 on 2026-07-28 21:05

from django.contrib.postgres.operations import AddIndexConcurrently, RemoveIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    # index builds on the tickets table can't take ACCESS EXCLUSIVE for the duration, so the new indexes are
    # created concurrently under their own names before the old ones are dropped concurrently
    atomic = False

    dependencies = [
        ("orgs", "0186_alter_export_id_alter_invitation_id_and_more"),
        ("tickets", "0088_alter_shortcut_id_alter_team_id"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="ticket",
            index=models.Index(fields=["org", "-status", "-last_activity_on", "-id"], name="tickets_org_status_desc"),
        ),
        AddIndexConcurrently(
            model_name="ticket",
            index=models.Index(
                fields=["org", "assignee", "-status", "-last_activity_on", "-id"],
                name="tickets_org_assign_status_desc",
            ),
        ),
        RemoveIndexConcurrently(
            model_name="ticket",
            name="tickets_org_status",
        ),
        RemoveIndexConcurrently(
            model_name="ticket",
            name="tickets_org_assignee_status",
        ),
    ]
