# Generated by Django 6.0.7 on 2026-08-04 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0188_reset_dropped_languages"),
        ("tickets", "0091_remove_ticket_tickets_org_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="shortcut",
            index=models.Index(fields=["org", "modified_on"], name="shortcut_by_modified"),
        ),
    ]
