# Generated by Django 5.2.2 on 2025-07-02 14:48

from django.db import migrations

from . import InstallSQL


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        InstallSQL("0008_functions"),
        InstallSQL("0008_triggers"),
    ]
