# Generated by Django 5.2.14 on 2026-07-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ivr", "0039_backfill_call_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="error_reason",
            field=models.CharField(
                choices=[
                    ("P", "Provider"),
                    ("B", "Busy"),
                    ("N", "No Answer"),
                    ("M", "Answering Machine"),
                    ("S", "Workspace suspended"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
