# Generated by Django 6.0.7 on 2026-07-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ivr", "0040_alter_call_error_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
