# Generated by Django 2.2.20 on 2021-05-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triggers", "0017_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trigger",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("K", "Keyword Trigger"),
                    ("S", "Schedule Trigger"),
                    ("V", "Inbound Call Trigger"),
                    ("M", "Missed Call Trigger"),
                    ("N", "New Conversation Trigger"),
                    ("R", "Referral Trigger"),
                    ("C", "Catch All Trigger"),
                ],
                default="K",
                max_length=1,
            ),
        ),
    ]
