# Generated by Django 2.2.20 on 2021-05-26 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triggers", "0017_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trigger",
            name="groups",
            field=models.ManyToManyField(
                help_text="The groups to broadcast the flow to",
                related_name="triggers",
                to="contacts.ContactGroup",
                verbose_name="Groups",
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="triggers", to="orgs.Org"
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("K", "Keyword Trigger"),
                    ("S", "Schedule Trigger"),
                    ("V", "Inbound Call Trigger"),
                    ("M", "Missed Call Trigger"),
                    ("N", "New Conversation Trigger"),
                    ("R", "Referral Trigger"),
                    ("T", "Closed Ticket"),
                    ("C", "Catch All Trigger"),
                ],
                default="K",
                max_length=1,
            ),
        ),
    ]
