# Generated by Django 5.2.10 on 2026-03-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triggers", "0043_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trigger",
            name="match_type",
            field=models.CharField(
                choices=[("O", "Message contains only the keyword"), ("F", "Message starts with the keyword")],
                max_length=1,
                null=True,
            ),
        ),
    ]
