# Generated by Django 6.0.7 on 2026-08-04 12:00

from django.db import migrations


def release_optin_triggers(apps, schema_editor):
    Trigger = apps.get_model("triggers", "Trigger")

    num_released = Trigger.objects.filter(trigger_type__in=("I", "O"), is_active=True).update(is_active=False)
    if num_released:
        print(f"Released {num_released} opt-in and opt-out triggers")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    release_optin_triggers(apps, None)


class Migration(migrations.Migration):
    dependencies = [
        ("triggers", "0045_alter_trigger_id"),
    ]

    operations = [
        migrations.RunPython(release_optin_triggers, migrations.RunPython.noop),
    ]
