# Generated by Django 6.0.7 on 2026-08-17 10:00

from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):
    dependencies = [
        ("triggers", "0046_release_optin_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, null=True),
        ),
    ]
