# Generated by Django 6.0.7 on 2026-08-17 10:05

import itertools
from uuid import uuid4

from django.db import migrations


def backfill_trigger_uuids(apps, schema_editor):
    Trigger = apps.get_model("triggers", "Trigger")

    num_updated = 0

    for batch in itertools.batched(Trigger.objects.filter(uuid__isnull=True).order_by("id"), 100):
        for trigger in batch:
            trigger.uuid = uuid4()
            num_updated += 1

        Trigger.objects.bulk_update(batch, ["uuid"])
        print(f"Updated {num_updated} trigger records with UUIDs")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    backfill_trigger_uuids(apps, None)


class Migration(migrations.Migration):
    dependencies = [
        ("triggers", "0047_trigger_uuid"),
    ]

    operations = [
        migrations.RunPython(backfill_trigger_uuids, migrations.RunPython.noop),
    ]
