# Generated by Django 6.0.7 on 2026-08-17 10:10

from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):
    dependencies = [
        ("triggers", "0048_backfill_trigger_uuids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trigger",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, unique=True),
        ),
    ]
